from __future__ import annotations

"""DateTime helper functions for WASM binary backend.

Direct port of the WAT DateTime helpers to the binary emitter.
"""

from flux_proto.wasm.binary import (
    FuncBody, I32, I64, F64,
    OP_I32_LOAD8_U, OP_I64_LOAD, OP_I32_STORE8,
    OP_I32_CONST, OP_I64_CONST, OP_F64_CONST,
    OP_I32_EQZ, OP_I32_EQ, OP_I32_NE,
    OP_I64_EQZ, OP_I64_EQ, OP_I64_NE,
    OP_I64_LT_S, OP_I64_LT_U, OP_I64_GT_S, OP_I64_GT_U, OP_I64_LE_S, OP_I64_GE_S,
    OP_I32_LT_U, OP_I32_GE_U, OP_I32_ADD, OP_I32_SUB, OP_I32_MUL, OP_I32_AND, OP_I32_OR,
    OP_I64_ADD, OP_I64_SUB, OP_I64_MUL, OP_I64_DIV_S, OP_I64_DIV_U,
    OP_I64_REM_S, OP_I64_REM_U, OP_I64_AND, OP_I64_OR, OP_I64_SHL, OP_I64_SHR_U,
    OP_I64_EXTEND_I32_U, OP_I32_WRAP_I64,
    OP_RETURN, OP_DROP, OP_SELECT, OP_IF, OP_ELSE, OP_END,
    OP_BR, OP_BR_IF,
    encode_memarg, sleb128,
)


def _mem(fb: FuncBody, op: int, align: int, off: int = 0) -> None:
    fb.byte(op)
    fb.put(encode_memarg(align, off))


def _call(fb: FuncBody, idx: int) -> None:
    fb.byte(0x10)
    fb.uleb(idx)


def _br_depth(fb: FuncBody, pos: int) -> int:
    return fb.label_depth - pos


class DateTimeHelpers:
    """Constructs DateTime helper functions for the WASM module."""

    def __init__(self, cg) -> None:
        self.cg = cg
        self.mod = cg._mod
        self.helpers = cg._helper_funcs

        zero_i64 = bytes([OP_I64_CONST]) + sleb128(0)
        self.g_y = self.mod.add_global(I64, True, zero_i64)
        self.g_m = self.mod.add_global(I64, True, zero_i64)
        self.g_d = self.mod.add_global(I64, True, zero_i64)
        self.g_h = self.mod.add_global(I64, True, zero_i64)
        self.g_mi = self.mod.add_global(I64, True, zero_i64)
        self.g_s = self.mod.add_global(I64, True, zero_i64)
        self.g_ms = self.mod.add_global(I64, True, zero_i64)
        self.g_us = self.mod.add_global(I64, True, zero_i64)
        self.g_ns = self.mod.add_global(I64, True, zero_i64)
        self.g_days = self.mod.add_global(I64, True, zero_i64)

    def add(self, key: str, params: list[int], results: list[int]) -> int:
        t = self.mod.add_type(params, results)
        fidx = self.mod.add_function(t)
        self.helpers[key] = fidx
        return fidx

    def add_code(self, fb: FuncBody) -> None:
        self.mod.add_code(fb.get_locals_decls(), fb.get_bytes())

    def build_dt_floor_div(self) -> None:
        fb = FuncBody(2)
        q = fb.new_i64()
        r = fb.new_i64()
        fb.local_get(0)
        fb.local_get(1)
        fb.byte(OP_I64_DIV_S)
        fb.local_set(q)
        fb.local_get(0)
        fb.local_get(1)
        fb.byte(OP_I64_REM_S)
        fb.local_set(r)
        fb.local_get(0)
        fb.i64_const(0)
        fb.byte(OP_I64_LT_S)
        fb.local_get(r)
        fb.i64_const(0)
        fb.byte(OP_I64_NE)
        fb.byte(OP_I32_AND)
        fb.emit_if()
        fb.local_get(q)
        fb.i64_const(1)
        fb.byte(OP_I64_SUB)
        fb.local_set(q)
        fb.emit_end()
        fb.local_get(q)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_floor_rem(self) -> None:
        fb = FuncBody(2)
        fb.local_get(0)
        fb.local_get(0)
        fb.local_get(1)
        _call(fb, self.helpers["$dt_floor_div"])
        fb.local_get(1)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_I64_SUB)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_split(self) -> None:
        fb = FuncBody(1)
        sec = fb.new_i64()
        frac = fb.new_i64()
        days = fb.new_i64()
        rem_sec = fb.new_i64()
        z = fb.new_i64()
        era = fb.new_i64()
        doe = fb.new_i64()
        yoe = fb.new_i64()
        y = fb.new_i64()
        doy = fb.new_i64()
        mp = fb.new_i64()
        d = fb.new_i64()
        m = fb.new_i64()

        fb.local_get(0)
        fb.i64_const(1000000000)
        _call(fb, self.helpers["$dt_floor_div"])
        fb.local_set(sec)

        fb.local_get(0)
        fb.i64_const(1000000000)
        _call(fb, self.helpers["$dt_floor_rem"])
        fb.local_set(frac)

        fb.local_get(sec)
        fb.i64_const(86400)
        _call(fb, self.helpers["$dt_floor_div"])
        fb.local_set(days)

        fb.local_get(sec)
        fb.i64_const(86400)
        _call(fb, self.helpers["$dt_floor_rem"])
        fb.local_set(rem_sec)

        fb.local_get(days)
        fb.global_set(self.g_days)

        fb.local_get(days)
        fb.i64_const(719468)
        fb.byte(OP_I64_ADD)
        fb.local_set(z)

        fb.local_get(z)
        fb.local_get(z)
        fb.i64_const(146096)
        fb.byte(OP_I64_SUB)
        fb.local_get(z)
        fb.i64_const(0)
        fb.byte(OP_I64_GE_S)
        fb.byte(OP_SELECT)
        fb.i64_const(146097)
        _call(fb, self.helpers["$dt_floor_div"])
        fb.local_set(era)

        fb.local_get(z)
        fb.local_get(era)
        fb.i64_const(146097)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_I64_SUB)
        fb.local_set(doe)

        fb.local_get(doe)
        fb.local_get(doe)
        fb.i64_const(1460)
        fb.byte(OP_I64_DIV_S)
        fb.byte(OP_I64_SUB)
        fb.local_get(doe)
        fb.i64_const(36524)
        fb.byte(OP_I64_DIV_S)
        fb.byte(OP_I64_ADD)
        fb.local_get(doe)
        fb.i64_const(146096)
        fb.byte(OP_I64_DIV_S)
        fb.byte(OP_I64_SUB)
        fb.i64_const(365)
        fb.byte(OP_I64_DIV_S)
        fb.local_set(yoe)

        fb.local_get(yoe)
        fb.local_get(era)
        fb.i64_const(400)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_I64_ADD)
        fb.local_set(y)

        fb.local_get(doe)
        fb.i64_const(365)
        fb.local_get(yoe)
        fb.byte(OP_I64_MUL)
        fb.local_get(yoe)
        fb.i64_const(4)
        fb.byte(OP_I64_DIV_S)
        fb.byte(OP_I64_ADD)
        fb.local_get(yoe)
        fb.i64_const(100)
        fb.byte(OP_I64_DIV_S)
        fb.byte(OP_I64_SUB)
        fb.byte(OP_I64_SUB)
        fb.local_set(doy)

        fb.i64_const(5)
        fb.local_get(doy)
        fb.byte(OP_I64_MUL)
        fb.i64_const(2)
        fb.byte(OP_I64_ADD)
        fb.i64_const(153)
        fb.byte(OP_I64_DIV_S)
        fb.local_set(mp)

        fb.local_get(doy)
        fb.i64_const(153)
        fb.local_get(mp)
        fb.byte(OP_I64_MUL)
        fb.i64_const(2)
        fb.byte(OP_I64_ADD)
        fb.i64_const(5)
        fb.byte(OP_I64_DIV_S)
        fb.byte(OP_I64_SUB)
        fb.i64_const(1)
        fb.byte(OP_I64_ADD)
        fb.local_set(d)

        fb.local_get(mp)
        fb.i64_const(3)
        fb.byte(OP_I64_ADD)
        fb.local_get(mp)
        fb.i64_const(9)
        fb.byte(OP_I64_SUB)
        fb.local_get(mp)
        fb.i64_const(10)
        fb.byte(OP_I64_LT_S)
        fb.byte(OP_SELECT)
        fb.local_set(m)

        fb.local_get(m)
        fb.i64_const(2)
        fb.byte(OP_I64_LE_S)
        fb.emit_if()
        fb.local_get(y)
        fb.i64_const(1)
        fb.byte(OP_I64_ADD)
        fb.local_set(y)
        fb.emit_end()

        fb.local_get(y)
        fb.global_set(self.g_y)
        fb.local_get(m)
        fb.global_set(self.g_m)
        fb.local_get(d)
        fb.global_set(self.g_d)

        fb.local_get(rem_sec)
        fb.i64_const(3600)
        fb.byte(OP_I64_DIV_S)
        fb.global_set(self.g_h)

        fb.local_get(rem_sec)
        fb.i64_const(3600)
        fb.byte(OP_I64_REM_S)
        fb.i64_const(60)
        fb.byte(OP_I64_DIV_S)
        fb.global_set(self.g_mi)

        fb.local_get(rem_sec)
        fb.i64_const(60)
        fb.byte(OP_I64_REM_S)
        fb.global_set(self.g_s)

        fb.local_get(frac)
        fb.i64_const(1000000)
        fb.byte(OP_I64_DIV_S)
        fb.global_set(self.g_ms)

        fb.local_get(frac)
        fb.i64_const(1000)
        fb.byte(OP_I64_DIV_S)
        fb.global_set(self.g_us)

        fb.local_get(frac)
        fb.global_set(self.g_ns)

        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_is_leap_year_val(self) -> None:
        fb = FuncBody(1)
        fb.local_get(0)
        fb.i64_const(400)
        fb.byte(OP_I64_REM_S)
        fb.byte(OP_I64_EQZ)
        fb.emit_if()
        fb.i64_const(1)
        fb.byte(OP_RETURN)
        fb.emit_end()

        fb.local_get(0)
        fb.i64_const(100)
        fb.byte(OP_I64_REM_S)
        fb.byte(OP_I64_EQZ)
        fb.emit_if()
        fb.i64_const(0)
        fb.byte(OP_RETURN)
        fb.emit_end()

        fb.local_get(0)
        fb.i64_const(4)
        fb.byte(OP_I64_REM_S)
        fb.byte(OP_I64_EQZ)
        fb.emit_if()
        fb.i64_const(1)
        fb.byte(OP_RETURN)
        fb.emit_end()

        fb.i64_const(0)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_days_in_month_val(self) -> None:
        fb = FuncBody(2)
        fb.local_get(1)
        fb.i64_const(2)
        fb.byte(OP_I64_EQ)
        fb.emit_if()
        fb.i64_const(29)
        fb.i64_const(28)
        fb.local_get(0)
        _call(fb, self.helpers["$dt_is_leap_year_val"])
        fb.i64_const(1)
        fb.byte(OP_I64_EQ)
        fb.byte(OP_SELECT)
        fb.byte(OP_RETURN)
        fb.emit_end()

        for m_val in (4, 6, 9, 11):
            fb.local_get(1)
            fb.i64_const(m_val)
            fb.byte(OP_I64_EQ)
            fb.emit_if()
            fb.i64_const(30)
            fb.byte(OP_RETURN)
            fb.emit_end()

        fb.i64_const(31)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_get_comp(self) -> None:
        fb = FuncBody(2)
        y = fb.new_i64()
        m = fb.new_i64()
        d = fb.new_i64()
        w = fb.new_i64()

        fb.local_get(0)
        _call(fb, self.helpers["$dt_split"])
        fb.global_get(self.g_y)
        fb.local_set(y)
        fb.global_get(self.g_m)
        fb.local_set(m)
        fb.global_get(self.g_d)
        fb.local_set(d)

        # 0: year
        fb.local_get(1)
        fb.i32_const(0)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(y)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 1: month
        fb.local_get(1)
        fb.i32_const(1)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(m)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 2: day
        fb.local_get(1)
        fb.i32_const(2)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(d)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 3: hour
        fb.local_get(1)
        fb.i32_const(3)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.global_get(self.g_h)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 4: minute
        fb.local_get(1)
        fb.i32_const(4)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.global_get(self.g_mi)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 5: second
        fb.local_get(1)
        fb.i32_const(5)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.global_get(self.g_s)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 6: millisecond
        fb.local_get(1)
        fb.i32_const(6)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.global_get(self.g_ms)
        fb.i64_const(1000)
        fb.byte(OP_I64_REM_S)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 7: microsecond
        fb.local_get(1)
        fb.i32_const(7)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.global_get(self.g_us)
        fb.i64_const(1000000)
        fb.byte(OP_I64_REM_S)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 8: nanosecond
        fb.local_get(1)
        fb.i32_const(8)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.global_get(self.g_ns)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 9: weekday (Monday=1..Sunday=7)
        fb.local_get(1)
        fb.i32_const(9)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.global_get(self.g_days)
        fb.i64_const(3)
        fb.byte(OP_I64_ADD)
        fb.i64_const(7)
        fb.byte(OP_I64_REM_S)
        fb.local_set(w)
        fb.local_get(w)
        fb.i64_const(0)
        fb.byte(OP_I64_LT_S)
        fb.emit_if()
        fb.local_get(w)
        fb.i64_const(7)
        fb.byte(OP_I64_ADD)
        fb.local_set(w)
        fb.emit_end()
        fb.local_get(w)
        fb.i64_const(1)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 10: dayOfYear
        fb.local_get(1)
        fb.i32_const(10)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.global_get(self.g_days)
        fb.local_get(y)
        fb.i64_const(1)
        fb.i64_const(1)
        _call(fb, self.helpers["$days_from_civil"])
        fb.byte(OP_I64_SUB)
        fb.i64_const(1)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 11: daysInMonth
        fb.local_get(1)
        fb.i32_const(11)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(y)
        fb.local_get(m)
        _call(fb, self.helpers["$dt_days_in_month_val"])
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 12: quarter
        fb.local_get(1)
        fb.i32_const(12)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(m)
        fb.i64_const(1)
        fb.byte(OP_I64_SUB)
        fb.i64_const(3)
        fb.byte(OP_I64_DIV_S)
        fb.i64_const(1)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 13: isLeapYear
        fb.local_get(1)
        fb.i32_const(13)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(y)
        _call(fb, self.helpers["$dt_is_leap_year_val"])
        fb.byte(OP_RETURN)
        fb.emit_end()

        # 14: isWeekend
        fb.local_get(1)
        fb.i32_const(14)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(0)
        fb.i32_const(9)
        _call(fb, self.helpers["$dt_get_comp"])
        fb.local_set(w)
        fb.i64_const(1)
        fb.i64_const(0)
        fb.local_get(w)
        fb.i64_const(6)
        fb.byte(OP_I64_EQ)
        fb.local_get(w)
        fb.i64_const(7)
        fb.byte(OP_I64_EQ)
        fb.byte(OP_I32_OR)
        fb.byte(OP_SELECT)
        fb.byte(OP_RETURN)
        fb.emit_end()

        fb.i64_const(0)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_create_date(self) -> None:
        fb = FuncBody(3)
        fb.local_get(0)
        fb.local_get(1)
        fb.local_get(2)
        _call(fb, self.helpers["$days_from_civil"])
        fb.i64_const(86400000000000)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_create_time(self) -> None:
        fb = FuncBody(3)
        fb.local_get(0)
        fb.i64_const(3600)
        fb.byte(OP_I64_MUL)
        fb.local_get(1)
        fb.i64_const(60)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_I64_ADD)
        fb.local_get(2)
        fb.byte(OP_I64_ADD)
        fb.i64_const(1000000000)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_create_time_full(self) -> None:
        fb = FuncBody(6)
        tot = fb.new_i64()
        fb.local_get(0)
        fb.local_get(1)
        fb.local_get(2)
        _call(fb, self.helpers["$dt_create_time"])
        fb.local_set(tot)

        fb.local_get(tot)
        fb.local_get(3)
        fb.i64_const(1000000)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_I64_ADD)
        fb.local_set(tot)

        fb.local_get(tot)
        fb.local_get(4)
        fb.i64_const(1000)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_I64_ADD)
        fb.local_set(tot)

        fb.local_get(tot)
        fb.local_get(5)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_now(self) -> None:
        fb = FuncBody(0)
        wasi_off = self.cg._dt_wasi_off()
        fb.i32_const(0)
        fb.i64_const(0)
        fb.i32_const(wasi_off)
        _call(fb, self.helpers["$clock_time_get"])
        fb.byte(OP_DROP)
        fb.i32_const(wasi_off)
        _mem(fb, OP_I64_LOAD, 3, 0)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_monotonic_now(self) -> None:
        fb = FuncBody(0)
        wasi_off = self.cg._dt_wasi_off()
        fb.i32_const(1)
        fb.i64_const(0)
        fb.i32_const(wasi_off)
        _call(fb, self.helpers["$clock_time_get"])
        fb.byte(OP_DROP)
        fb.i32_const(wasi_off)
        _mem(fb, OP_I64_LOAD, 3, 0)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_today(self) -> None:
        fb = FuncBody(0)
        now = fb.new_i64()
        days = fb.new_i64()
        _call(fb, self.helpers["$dt_now"])
        fb.local_set(now)
        fb.local_get(now)
        _call(fb, self.helpers["$dt_split"])
        fb.global_get(self.g_y)
        fb.global_get(self.g_m)
        fb.global_get(self.g_d)
        _call(fb, self.helpers["$days_from_civil"])
        fb.local_set(days)
        fb.local_get(days)
        fb.i64_const(86400000000000)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_time(self) -> None:
        fb = FuncBody(0)
        now = fb.new_i64()
        sec = fb.new_i64()
        frac = fb.new_i64()
        rem_sec = fb.new_i64()
        _call(fb, self.helpers["$dt_now"])
        fb.local_set(now)
        fb.local_get(now)
        fb.i64_const(1000000000)
        fb.byte(OP_I64_DIV_S)
        fb.local_set(sec)
        fb.local_get(now)
        fb.i64_const(1000000000)
        fb.byte(OP_I64_REM_S)
        fb.local_set(frac)
        fb.local_get(sec)
        fb.i64_const(86400)
        fb.byte(OP_I64_REM_S)
        fb.local_set(rem_sec)
        fb.local_get(rem_sec)
        fb.i64_const(1000000000)
        fb.byte(OP_I64_MUL)
        fb.local_get(frac)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_add_months(self) -> None:
        fb = FuncBody(2)
        y = fb.new_i64()
        m = fb.new_i64()
        d = fb.new_i64()
        h = fb.new_i64()
        mi = fb.new_i64()
        s = fb.new_i64()
        frac = fb.new_i64()
        tot_m = fb.new_i64()
        ny = fb.new_i64()
        nm = fb.new_i64()
        dim = fb.new_i64()
        nd = fb.new_i64()
        day = fb.new_i64()
        sec = fb.new_i64()

        fb.local_get(0)
        _call(fb, self.helpers["$dt_split"])
        fb.global_get(self.g_y)
        fb.local_set(y)
        fb.global_get(self.g_m)
        fb.local_set(m)
        fb.global_get(self.g_d)
        fb.local_set(d)
        fb.global_get(self.g_h)
        fb.local_set(h)
        fb.global_get(self.g_mi)
        fb.local_set(mi)
        fb.global_get(self.g_s)
        fb.local_set(s)
        fb.global_get(self.g_ns)
        fb.local_set(frac)

        # tot_m = y * 12 + (m - 1) + months
        fb.local_get(y)
        fb.i64_const(12)
        fb.byte(OP_I64_MUL)
        fb.local_get(m)
        fb.i64_const(1)
        fb.byte(OP_I64_SUB)
        fb.byte(OP_I64_ADD)
        fb.local_get(1)
        fb.byte(OP_I64_ADD)
        fb.local_set(tot_m)

        # ny = dt_floor_div(tot_m, 12)
        fb.local_get(tot_m)
        fb.i64_const(12)
        _call(fb, self.helpers["$dt_floor_div"])
        fb.local_set(ny)

        # nm = dt_floor_rem(tot_m, 12) + 1
        fb.local_get(tot_m)
        fb.i64_const(12)
        _call(fb, self.helpers["$dt_floor_rem"])
        fb.i64_const(1)
        fb.byte(OP_I64_ADD)
        fb.local_set(nm)

        # dim = dt_days_in_month_val(ny, nm)
        fb.local_get(ny)
        fb.local_get(nm)
        _call(fb, self.helpers["$dt_days_in_month_val"])
        fb.local_set(dim)

        # nd = select(dim, d, d > dim)
        fb.local_get(dim)
        fb.local_get(d)
        fb.local_get(d)
        fb.local_get(dim)
        fb.byte(OP_I64_GT_S)
        fb.byte(OP_SELECT)
        fb.local_set(nd)

        # day = days_from_civil(ny, nm, nd)
        fb.local_get(ny)
        fb.local_get(nm)
        fb.local_get(nd)
        _call(fb, self.helpers["$days_from_civil"])
        fb.local_set(day)

        # sec = day * 86400 + h * 3600 + mi * 60 + s
        fb.local_get(day)
        fb.i64_const(86400)
        fb.byte(OP_I64_MUL)
        fb.local_get(h)
        fb.i64_const(3600)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_I64_ADD)
        fb.local_get(mi)
        fb.i64_const(60)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_I64_ADD)
        fb.local_get(s)
        fb.byte(OP_I64_ADD)
        fb.local_set(sec)

        # return sec * 1000000000 + frac
        fb.local_get(sec)
        fb.i64_const(1000000000)
        fb.byte(OP_I64_MUL)
        fb.local_get(frac)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_add_years(self) -> None:
        fb = FuncBody(2)
        fb.local_get(0)
        fb.local_get(1)
        fb.i64_const(12)
        fb.byte(OP_I64_MUL)
        _call(fb, self.helpers["$dt_add_months"])
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_months_between(self) -> None:
        fb = FuncBody(2)
        left = 0
        right = 1
        sign = fb.new_i64()
        tmp = fb.new_i64()
        ly = fb.new_i64()
        lm = fb.new_i64()
        ld = fb.new_i64()
        lh = fb.new_i64()
        lmi = fb.new_i64()
        ls = fb.new_i64()
        lfrac = fb.new_i64()
        ry = fb.new_i64()
        rm = fb.new_i64()
        rd = fb.new_i64()
        rh = fb.new_i64()
        rmi = fb.new_i64()
        rs = fb.new_i64()
        rfrac = fb.new_i64()
        mdiff = fb.new_i64()
        less = fb.new_i32()

        # if left == right: return 0
        fb.local_get(left)
        fb.local_get(right)
        fb.byte(OP_I64_EQ)
        fb.emit_if()
        fb.i64_const(0)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # if right >= left: sign = 1 else sign = -1; swap(left, right)
        fb.local_get(right)
        fb.local_get(left)
        fb.byte(OP_I64_GE_S)
        fb.emit_if()
        fb.i64_const(1)
        fb.local_set(sign)
        fb.emit_else()
        fb.i64_const(-1)
        fb.local_set(sign)
        fb.local_get(left)
        fb.local_set(tmp)
        fb.local_get(right)
        fb.local_set(left)
        fb.local_get(tmp)
        fb.local_set(right)
        fb.emit_end()

        # dt_split(left)
        fb.local_get(left)
        _call(fb, self.helpers["$dt_split"])
        fb.global_get(self.g_y)
        fb.local_set(ly)
        fb.global_get(self.g_m)
        fb.local_set(lm)
        fb.global_get(self.g_d)
        fb.local_set(ld)
        fb.global_get(self.g_h)
        fb.local_set(lh)
        fb.global_get(self.g_mi)
        fb.local_set(lmi)
        fb.global_get(self.g_s)
        fb.local_set(ls)
        fb.global_get(self.g_ns)
        fb.local_set(lfrac)

        # dt_split(right)
        fb.local_get(right)
        _call(fb, self.helpers["$dt_split"])
        fb.global_get(self.g_y)
        fb.local_set(ry)
        fb.global_get(self.g_m)
        fb.local_set(rm)
        fb.global_get(self.g_d)
        fb.local_set(rd)
        fb.global_get(self.g_h)
        fb.local_set(rh)
        fb.global_get(self.g_mi)
        fb.local_set(rmi)
        fb.global_get(self.g_s)
        fb.local_set(rs)
        fb.global_get(self.g_ns)
        fb.local_set(rfrac)

        # mdiff = (ry * 12 + rm) - (ly * 12 + lm)
        fb.local_get(ry)
        fb.i64_const(12)
        fb.byte(OP_I64_MUL)
        fb.local_get(rm)
        fb.byte(OP_I64_ADD)
        fb.local_get(ly)
        fb.i64_const(12)
        fb.byte(OP_I64_MUL)
        fb.local_get(lm)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_I64_SUB)
        fb.local_set(mdiff)

        fb.i32_const(0)
        fb.local_set(less)

        # day check
        fb.local_get(rd)
        fb.local_get(ld)
        fb.byte(OP_I64_LT_S)
        fb.emit_if()
        fb.i32_const(1)
        fb.local_set(less)
        fb.emit_else()
        fb.local_get(rd)
        fb.local_get(ld)
        fb.byte(OP_I64_EQ)
        fb.emit_if()

        # hour check
        fb.local_get(rh)
        fb.local_get(lh)
        fb.byte(OP_I64_LT_S)
        fb.emit_if()
        fb.i32_const(1)
        fb.local_set(less)
        fb.emit_else()
        fb.local_get(rh)
        fb.local_get(lh)
        fb.byte(OP_I64_EQ)
        fb.emit_if()

        # min check
        fb.local_get(rmi)
        fb.local_get(lmi)
        fb.byte(OP_I64_LT_S)
        fb.emit_if()
        fb.i32_const(1)
        fb.local_set(less)
        fb.emit_else()
        fb.local_get(rmi)
        fb.local_get(lmi)
        fb.byte(OP_I64_EQ)
        fb.emit_if()

        # sec check
        fb.local_get(rs)
        fb.local_get(ls)
        fb.byte(OP_I64_LT_S)
        fb.emit_if()
        fb.i32_const(1)
        fb.local_set(less)
        fb.emit_else()
        fb.local_get(rs)
        fb.local_get(ls)
        fb.byte(OP_I64_EQ)
        fb.emit_if()

        # frac check
        fb.local_get(rfrac)
        fb.local_get(lfrac)
        fb.byte(OP_I64_LT_S)
        fb.emit_if()
        fb.i32_const(1)
        fb.local_set(less)
        fb.emit_end()

        fb.emit_end()
        fb.emit_end()
        fb.emit_end()
        fb.emit_end()
        fb.emit_end()
        fb.emit_end()
        fb.emit_end()
        fb.emit_end()

        fb.local_get(less)
        fb.emit_if()
        fb.local_get(mdiff)
        fb.i64_const(1)
        fb.byte(OP_I64_SUB)
        fb.local_set(mdiff)
        fb.emit_end()

        fb.local_get(mdiff)
        fb.local_get(sign)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_years_between(self) -> None:
        fb = FuncBody(2)
        fb.local_get(0)
        fb.local_get(1)
        _call(fb, self.helpers["$dt_months_between"])
        fb.i64_const(12)
        fb.byte(OP_I64_DIV_S)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_write_2d(self) -> None:
        fb = FuncBody(2)
        # ptr[0] = (val / 10) + 48
        fb.local_get(0)
        fb.local_get(1)
        fb.i64_const(10)
        fb.byte(OP_I64_DIV_U)
        fb.i64_const(48)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_I32_WRAP_I64)
        _mem(fb, OP_I32_STORE8, 0, 0)
        # ptr[1] = (val % 10) + 48
        fb.local_get(0)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.local_get(1)
        fb.i64_const(10)
        fb.byte(OP_I64_REM_U)
        fb.i64_const(48)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_I32_WRAP_I64)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_write_4d(self) -> None:
        fb = FuncBody(2)
        fb.local_get(0)
        fb.local_get(1)
        fb.i64_const(100)
        fb.byte(OP_I64_DIV_U)
        _call(fb, self.helpers["$dt_write_2d"])
        fb.local_get(0)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_get(1)
        fb.i64_const(100)
        fb.byte(OP_I64_REM_U)
        _call(fb, self.helpers["$dt_write_2d"])
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_to_iso(self) -> None:
        fb = FuncBody(1)
        p = fb.new_i32()
        fb.i32_const(32)
        _call(fb, self.helpers["$flux_alloc"])
        fb.local_set(p)
        fb.local_get(0)
        fb.local_get(p)
        _call(fb, self.helpers["$dt_to_str"])
        fb.byte(OP_DROP)
        fb.local_get(p)
        fb.byte(OP_I64_EXTEND_I32_U)
        fb.i64_const(32)
        fb.byte(OP_I64_SHL)
        fb.i64_const(30)
        fb.byte(OP_I64_OR)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_to_timezone(self) -> None:
        fb = FuncBody(2)
        off_sec = fb.new_i64()
        loc_nanos = fb.new_i64()
        p = fb.new_i32()
        len_v = fb.new_i32()
        sign = fb.new_i32()
        abs_s = fb.new_i64()
        oh = fb.new_i64()
        om = fb.new_i64()

        tz_sp = self.cg._fat_const("America/Sao_Paulo")
        tz_brt = self.cg._fat_const("BRT")

        fb.i64_const(0)
        fb.local_set(off_sec)

        fb.local_get(1)
        fb.i64_const(tz_sp)
        _call(fb, self.helpers["$streq"])
        fb.local_get(1)
        fb.i64_const(tz_brt)
        _call(fb, self.helpers["$streq"])
        fb.byte(OP_I32_OR)
        fb.emit_if()
        fb.i64_const(-10800)
        fb.local_set(off_sec)
        fb.emit_end()

        fb.local_get(0)
        fb.local_get(off_sec)
        fb.i64_const(1000000000)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_I64_ADD)
        fb.local_set(loc_nanos)

        fb.i32_const(40)
        _call(fb, self.helpers["$flux_alloc"])
        fb.local_set(p)

        fb.local_get(loc_nanos)
        fb.local_get(p)
        _call(fb, self.helpers["$dt_to_str"])
        fb.byte(OP_DROP)

        fb.local_get(off_sec)
        fb.byte(OP_I64_EQZ)
        fb.emit_if()
        fb.i32_const(30)
        fb.local_set(len_v)
        fb.emit_else()
        fb.i32_const(43)
        fb.i32_const(45)
        fb.local_get(off_sec)
        fb.i64_const(0)
        fb.byte(OP_I64_GE_S)
        fb.byte(OP_SELECT)
        fb.local_set(sign)

        fb.local_get(off_sec)
        fb.i64_const(0)
        fb.local_get(off_sec)
        fb.byte(OP_I64_SUB)
        fb.local_get(off_sec)
        fb.i64_const(0)
        fb.byte(OP_I64_GE_S)
        fb.byte(OP_SELECT)
        fb.local_set(abs_s)

        fb.local_get(abs_s)
        fb.i64_const(3600)
        fb.byte(OP_I64_DIV_S)
        fb.local_set(oh)

        fb.local_get(abs_s)
        fb.i64_const(3600)
        fb.byte(OP_I64_REM_S)
        fb.i64_const(60)
        fb.byte(OP_I64_DIV_S)
        fb.local_set(om)

        fb.local_get(p)
        fb.i32_const(29)
        fb.byte(OP_I32_ADD)
        fb.local_get(sign)
        _mem(fb, OP_I32_STORE8, 0, 0)

        fb.local_get(p)
        fb.i32_const(30)
        fb.byte(OP_I32_ADD)
        fb.local_get(oh)
        _call(fb, self.helpers["$dt_write_2d"])

        fb.local_get(p)
        fb.i32_const(32)
        fb.byte(OP_I32_ADD)
        fb.i32_const(58)
        _mem(fb, OP_I32_STORE8, 0, 0)

        fb.local_get(p)
        fb.i32_const(33)
        fb.byte(OP_I32_ADD)
        fb.local_get(om)
        _call(fb, self.helpers["$dt_write_2d"])

        fb.i32_const(35)
        fb.local_set(len_v)
        fb.emit_end()

        fb.local_get(p)
        fb.byte(OP_I64_EXTEND_I32_U)
        fb.i64_const(32)
        fb.byte(OP_I64_SHL)
        fb.local_get(len_v)
        fb.byte(OP_I64_EXTEND_I32_U)
        fb.byte(OP_I64_OR)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_utc_offset(self) -> None:
        fb = FuncBody(2)
        tz_sp = self.cg._fat_const("America/Sao_Paulo")
        tz_brt = self.cg._fat_const("BRT")
        fb.local_get(1)
        fb.i64_const(tz_sp)
        _call(fb, self.helpers["$streq"])
        fb.local_get(1)
        fb.i64_const(tz_brt)
        _call(fb, self.helpers["$streq"])
        fb.byte(OP_I32_OR)
        fb.emit_if()
        fb.f64_const(-3.0)
        fb.byte(OP_RETURN)
        fb.emit_end()
        fb.f64_const(0.0)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_format(self) -> None:
        fb = FuncBody(2)
        pptr = fb.new_i32()
        plen = fb.new_i32()
        pi = fb.new_i32()
        out = fb.new_i32()
        oi = fb.new_i32()
        c = fb.new_i32()
        nc = fb.new_i32()

        fb.local_get(0)
        _call(fb, self.helpers["$dt_split"])

        fb.local_get(1)
        fb.i64_const(32)
        fb.byte(OP_I64_SHR_U)
        fb.byte(OP_I32_WRAP_I64)
        fb.local_set(pptr)

        fb.local_get(1)
        fb.i64_const(0xFFFFFFFF)
        fb.byte(OP_I64_AND)
        fb.byte(OP_I32_WRAP_I64)
        fb.local_set(plen)

        fb.local_get(plen)
        fb.i32_const(64)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$flux_alloc"])
        fb.local_set(out)

        fb.i32_const(0)
        fb.local_set(pi)
        fb.i32_const(0)
        fb.local_set(oi)

        fb.emit_block()
        b_done = fb.label_depth
        fb.emit_loop()
        l_lp = fb.label_depth

        fb.local_get(pi)
        fb.local_get(plen)
        fb.byte(OP_I32_GE_U)
        fb.br_if(_br_depth(fb, b_done))

        fb.local_get(pptr)
        fb.local_get(pi)
        fb.byte(OP_I32_ADD)
        _mem(fb, OP_I32_LOAD8_U, 0, 0)
        fb.local_set(c)

        # if c == '%' (37) and pi + 1 < plen:
        fb.local_get(c)
        fb.i32_const(37)
        fb.byte(OP_I32_EQ)
        fb.local_get(pi)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.local_get(plen)
        fb.byte(OP_I32_LT_U)
        fb.byte(OP_I32_AND)
        fb.emit_if()

        fb.local_get(pptr)
        fb.local_get(pi)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        _mem(fb, OP_I32_LOAD8_U, 0, 0)
        fb.local_set(nc)

        fb.local_get(pi)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(pi)

        # %Y: Year (89)
        fb.local_get(nc)
        fb.i32_const(89)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(out)
        fb.local_get(oi)
        fb.byte(OP_I32_ADD)
        fb.global_get(self.g_y)
        _call(fb, self.helpers["$dt_write_4d"])
        fb.local_get(oi)
        fb.i32_const(4)
        fb.byte(OP_I32_ADD)
        fb.local_set(oi)
        fb.br(_br_depth(fb, l_lp))
        fb.emit_end()

        # %m: Month (109)
        fb.local_get(nc)
        fb.i32_const(109)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(out)
        fb.local_get(oi)
        fb.byte(OP_I32_ADD)
        fb.global_get(self.g_m)
        _call(fb, self.helpers["$dt_write_2d"])
        fb.local_get(oi)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(oi)
        fb.br(_br_depth(fb, l_lp))
        fb.emit_end()

        # %d: Day (100)
        fb.local_get(nc)
        fb.i32_const(100)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(out)
        fb.local_get(oi)
        fb.byte(OP_I32_ADD)
        fb.global_get(self.g_d)
        _call(fb, self.helpers["$dt_write_2d"])
        fb.local_get(oi)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(oi)
        fb.br(_br_depth(fb, l_lp))
        fb.emit_end()

        # %H: Hour (72)
        fb.local_get(nc)
        fb.i32_const(72)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(out)
        fb.local_get(oi)
        fb.byte(OP_I32_ADD)
        fb.global_get(self.g_h)
        _call(fb, self.helpers["$dt_write_2d"])
        fb.local_get(oi)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(oi)
        fb.br(_br_depth(fb, l_lp))
        fb.emit_end()

        # %M: Minute (77)
        fb.local_get(nc)
        fb.i32_const(77)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(out)
        fb.local_get(oi)
        fb.byte(OP_I32_ADD)
        fb.global_get(self.g_mi)
        _call(fb, self.helpers["$dt_write_2d"])
        fb.local_get(oi)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(oi)
        fb.br(_br_depth(fb, l_lp))
        fb.emit_end()

        # %S: Second (83)
        fb.local_get(nc)
        fb.i32_const(83)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.local_get(out)
        fb.local_get(oi)
        fb.byte(OP_I32_ADD)
        fb.global_get(self.g_s)
        _call(fb, self.helpers["$dt_write_2d"])
        fb.local_get(oi)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(oi)
        fb.br(_br_depth(fb, l_lp))
        fb.emit_end()

        # Unknown specifier: write '%' and nc
        fb.local_get(out)
        fb.local_get(oi)
        fb.byte(OP_I32_ADD)
        fb.i32_const(37)
        _mem(fb, OP_I32_STORE8, 0, 0)

        fb.local_get(out)
        fb.local_get(oi)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        fb.local_get(nc)
        _mem(fb, OP_I32_STORE8, 0, 0)

        fb.local_get(oi)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(oi)
        fb.br(_br_depth(fb, l_lp))

        fb.emit_end()

        # Normal character: write c
        fb.local_get(out)
        fb.local_get(oi)
        fb.byte(OP_I32_ADD)
        fb.local_get(c)
        _mem(fb, OP_I32_STORE8, 0, 0)

        fb.local_get(oi)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.local_set(oi)

        fb.local_get(pi)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.local_set(pi)
        fb.br(_br_depth(fb, l_lp))

        fb.emit_end()  # end loop
        fb.emit_end()  # end block

        fb.local_get(out)
        fb.byte(OP_I64_EXTEND_I32_U)
        fb.i64_const(32)
        fb.byte(OP_I64_SHL)
        fb.local_get(oi)
        fb.byte(OP_I64_EXTEND_I32_U)
        fb.byte(OP_I64_OR)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_dt_format_duration(self) -> None:
        fb = FuncBody(1)
        buf = fb.new_i32()
        cur = fb.new_i32()
        u = fb.new_i64()
        s = fb.new_i64()
        rem_ns = fb.new_i64()
        m = fb.new_i64()
        h = fb.new_i64()
        d = fb.new_i64()
        ms = fb.new_i64()

        fb.i32_const(64)
        _call(fb, self.helpers["$flux_alloc"])
        fb.local_set(buf)
        fb.i32_const(0)
        fb.local_set(cur)

        # if ns == 0: return "0s"
        fb.local_get(0)
        fb.byte(OP_I64_EQZ)
        fb.emit_if()
        fb.local_get(buf)
        fb.i32_const(48)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(buf)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.i32_const(115)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(buf)
        fb.byte(OP_I64_EXTEND_I32_U)
        fb.i64_const(32)
        fb.byte(OP_I64_SHL)
        fb.i64_const(2)
        fb.byte(OP_I64_OR)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # if ns < 0: buf[0] = '-'; cur = 1; u = -ns else u = ns
        fb.local_get(0)
        fb.i64_const(0)
        fb.byte(OP_I64_LT_S)
        fb.emit_if()
        fb.local_get(buf)
        fb.i32_const(45)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.i32_const(1)
        fb.local_set(cur)
        fb.i64_const(0)
        fb.local_get(0)
        fb.byte(OP_I64_SUB)
        fb.local_set(u)
        fb.emit_else()
        fb.local_get(0)
        fb.local_set(u)
        fb.emit_end()

        # s = u / 1_000_000_000, rem_ns = u % 1_000_000_000
        fb.local_get(u)
        fb.i64_const(1000000000)
        fb.byte(OP_I64_DIV_U)
        fb.local_set(s)
        fb.local_get(u)
        fb.i64_const(1000000000)
        fb.byte(OP_I64_REM_U)
        fb.local_set(rem_ns)

        def _ret_fat():
            fb.local_get(buf)
            fb.byte(OP_I64_EXTEND_I32_U)
            fb.i64_const(32)
            fb.byte(OP_I64_SHL)
            fb.local_get(cur)
            fb.byte(OP_I64_EXTEND_I32_U)
            fb.byte(OP_I64_OR)
            fb.byte(OP_RETURN)

        # if s == 0: sub-second formatting
        fb.local_get(s)
        fb.byte(OP_I64_EQZ)
        fb.emit_if()

        # if rem_ns % 1_000_000 == 0: {ms}ms
        fb.local_get(rem_ns)
        fb.i64_const(1000000)
        fb.byte(OP_I64_REM_U)
        fb.byte(OP_I64_EQZ)
        fb.emit_if()
        fb.local_get(cur)
        fb.local_get(rem_ns)
        fb.i64_const(1000000)
        fb.byte(OP_I64_DIV_U)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(109)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        fb.i32_const(115)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        _ret_fat()
        fb.emit_end()

        # if rem_ns % 1_000 == 0: {us}us
        fb.local_get(rem_ns)
        fb.i64_const(1000)
        fb.byte(OP_I64_REM_U)
        fb.byte(OP_I64_EQZ)
        fb.emit_if()
        fb.local_get(cur)
        fb.local_get(rem_ns)
        fb.i64_const(1000)
        fb.byte(OP_I64_DIV_U)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(117)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        fb.i32_const(115)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        _ret_fat()
        fb.emit_end()

        # {ns}ns
        fb.local_get(cur)
        fb.local_get(rem_ns)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(110)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        fb.i32_const(115)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        _ret_fat()

        fb.emit_end()  # end if s == 0

        # if s < 60: seconds + optional ms
        fb.local_get(s)
        fb.i64_const(60)
        fb.byte(OP_I64_LT_U)
        fb.emit_if()
        fb.local_get(cur)
        fb.local_get(s)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)

        fb.local_get(rem_ns)
        fb.i64_const(1000000)
        fb.byte(OP_I64_DIV_U)
        fb.local_set(ms)

        fb.local_get(ms)
        fb.i64_const(0)
        fb.byte(OP_I64_GT_U)
        fb.emit_if()
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(46)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)

        # write 3 digits of ms
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i64_const(48)
        fb.local_get(ms)
        fb.i64_const(100)
        fb.byte(OP_I64_DIV_U)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_I32_WRAP_I64)
        _mem(fb, OP_I32_STORE8, 0, 0)

        fb.local_get(buf)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        fb.i64_const(48)
        fb.local_get(ms)
        fb.i64_const(10)
        fb.byte(OP_I64_DIV_U)
        fb.i64_const(10)
        fb.byte(OP_I64_REM_U)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_I32_WRAP_I64)
        _mem(fb, OP_I32_STORE8, 0, 0)

        fb.local_get(buf)
        fb.local_get(cur)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        fb.i64_const(48)
        fb.local_get(ms)
        fb.i64_const(10)
        fb.byte(OP_I64_REM_U)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_I32_WRAP_I64)
        _mem(fb, OP_I32_STORE8, 0, 0)

        fb.local_get(cur)
        fb.i32_const(3)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.emit_end()

        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(115)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        _ret_fat()
        fb.emit_end()  # end if s < 60

        # m = s / 60, s = s % 60
        fb.local_get(s)
        fb.i64_const(60)
        fb.byte(OP_I64_DIV_U)
        fb.local_set(m)
        fb.local_get(s)
        fb.i64_const(60)
        fb.byte(OP_I64_REM_U)
        fb.local_set(s)

        # if m < 60: {m}m {s}s
        fb.local_get(m)
        fb.i64_const(60)
        fb.byte(OP_I64_LT_U)
        fb.emit_if()
        fb.local_get(cur)
        fb.local_get(m)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(109)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        fb.i32_const(32)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)

        fb.local_get(cur)
        fb.local_get(s)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(115)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        _ret_fat()
        fb.emit_end()  # end if m < 60

        # h = m / 60, m = m % 60
        fb.local_get(m)
        fb.i64_const(60)
        fb.byte(OP_I64_DIV_U)
        fb.local_set(h)
        fb.local_get(m)
        fb.i64_const(60)
        fb.byte(OP_I64_REM_U)
        fb.local_set(m)

        # if h < 24: {h}h {m}m {s}s
        fb.local_get(h)
        fb.i64_const(24)
        fb.byte(OP_I64_LT_U)
        fb.emit_if()
        fb.local_get(cur)
        fb.local_get(h)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(104)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        fb.i32_const(32)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)

        fb.local_get(cur)
        fb.local_get(m)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(109)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        fb.i32_const(32)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)

        fb.local_get(cur)
        fb.local_get(s)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(115)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        _ret_fat()
        fb.emit_end()  # end if h < 24

        # d = h / 24, h = h % 24: {d}d {h}h {m}m {s}s
        fb.local_get(h)
        fb.i64_const(24)
        fb.byte(OP_I64_DIV_U)
        fb.local_set(d)
        fb.local_get(h)
        fb.i64_const(24)
        fb.byte(OP_I64_REM_U)
        fb.local_set(h)

        fb.local_get(cur)
        fb.local_get(d)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(100)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        fb.i32_const(32)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)

        fb.local_get(cur)
        fb.local_get(h)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(104)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        fb.i32_const(32)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)

        fb.local_get(cur)
        fb.local_get(m)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(109)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.byte(OP_I32_ADD)
        fb.i32_const(32)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(2)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)

        fb.local_get(cur)
        fb.local_get(s)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        _call(fb, self.helpers["$i64_to_str"])
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        fb.local_get(buf)
        fb.local_get(cur)
        fb.byte(OP_I32_ADD)
        fb.i32_const(115)
        _mem(fb, OP_I32_STORE8, 0, 0)
        fb.local_get(cur)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.local_set(cur)
        _ret_fat()
        self.add_code(fb)

    def build_dt_parse_iso(self) -> None:
        fb = FuncBody(1)
        ptr = fb.new_i32()
        len_v = fb.new_i32()
        c = fb.new_i32()
        cneg = fb.new_i32()
        y = fb.new_i64()
        mo = fb.new_i64()
        d = fb.new_i64()
        h = fb.new_i64()
        mi = fb.new_i64()
        s = fb.new_i64()
        nanos = fb.new_i64()
        delta = fb.new_i64()
        secs = fb.new_i64()
        day = fb.new_i64()

        dt_pos = self.cg._dt_pos
        dt_ok = self.cg._dt_ok

        fb.local_get(0)
        fb.i64_const(32)
        fb.byte(OP_I64_SHR_U)
        fb.byte(OP_I32_WRAP_I64)
        fb.local_set(ptr)

        fb.local_get(0)
        fb.i64_const(0xFFFFFFFF)
        fb.byte(OP_I64_AND)
        fb.byte(OP_I32_WRAP_I64)
        fb.local_set(len_v)

        fb.i32_const(0)
        fb.global_set(dt_pos)
        fb.i32_const(1)
        fb.global_set(dt_ok)

        # Skip leading whitespace
        fb.emit_block()
        b_ws = fb.label_depth
        fb.emit_loop()
        l_ws = fb.label_depth
        fb.global_get(dt_pos)
        fb.local_get(len_v)
        fb.byte(OP_I32_GE_U)
        fb.br_if(_br_depth(fb, b_ws))
        fb.local_get(ptr)
        fb.global_get(dt_pos)
        fb.byte(OP_I32_ADD)
        _mem(fb, OP_I32_LOAD8_U, 0, 0)
        fb.local_set(c)
        fb.local_get(c)
        fb.i32_const(32)
        fb.byte(OP_I32_EQ)
        fb.local_get(c)
        fb.i32_const(9)
        fb.byte(OP_I32_EQ)
        fb.byte(OP_I32_OR)
        fb.emit_if()
        fb.global_get(dt_pos)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.global_set(dt_pos)
        fb.br(_br_depth(fb, l_ws))
        fb.emit_else()
        fb.br(_br_depth(fb, b_ws))
        fb.emit_end()
        fb.emit_end()
        fb.emit_end()

        fb.i64_const(0)
        fb.local_set(nanos)
        fb.i64_const(0)
        fb.local_set(delta)

        # YYYY-
        fb.local_get(ptr)
        fb.local_get(len_v)
        fb.i32_const(4)
        fb.i32_const(45)
        _call(fb, self.helpers["$dt_num"])
        fb.local_set(y)

        # MM-
        fb.local_get(ptr)
        fb.local_get(len_v)
        fb.i32_const(2)
        fb.i32_const(45)
        _call(fb, self.helpers["$dt_num"])
        fb.local_set(mo)

        # DD with 'T' (84) or fallback to ' ' (32)
        fb.local_get(ptr)
        fb.local_get(len_v)
        fb.i32_const(2)
        fb.i32_const(84)
        _call(fb, self.helpers["$dt_num"])
        fb.local_set(d)

        fb.global_get(dt_ok)
        fb.byte(OP_I32_EQZ)
        fb.emit_if()
        fb.global_get(dt_pos)
        fb.i32_const(1)
        fb.byte(OP_I32_SUB)
        fb.global_set(dt_pos)
        fb.global_get(dt_pos)
        fb.local_get(len_v)
        fb.byte(OP_I32_LT_U)
        fb.emit_if()
        fb.local_get(ptr)
        fb.global_get(dt_pos)
        fb.byte(OP_I32_ADD)
        _mem(fb, OP_I32_LOAD8_U, 0, 0)
        fb.local_set(c)
        fb.local_get(c)
        fb.i32_const(32)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.i32_const(1)
        fb.global_set(dt_ok)
        fb.global_get(dt_pos)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.global_set(dt_pos)
        fb.emit_end()
        fb.emit_end()
        fb.emit_end()

        # HH:
        fb.local_get(ptr)
        fb.local_get(len_v)
        fb.i32_const(2)
        fb.i32_const(58)
        _call(fb, self.helpers["$dt_num"])
        fb.local_set(h)

        # MM:
        fb.local_get(ptr)
        fb.local_get(len_v)
        fb.i32_const(2)
        fb.i32_const(58)
        _call(fb, self.helpers["$dt_num"])
        fb.local_set(mi)

        # SS
        fb.local_get(ptr)
        fb.local_get(len_v)
        fb.i32_const(2)
        _call(fb, self.helpers["$dt_num0"])
        fb.local_set(s)

        # Fractional seconds
        fb.global_get(dt_ok)
        fb.emit_if()
        fb.global_get(dt_pos)
        fb.local_get(len_v)
        fb.byte(OP_I32_LT_U)
        fb.emit_if()
        fb.local_get(ptr)
        fb.global_get(dt_pos)
        fb.byte(OP_I32_ADD)
        _mem(fb, OP_I32_LOAD8_U, 0, 0)
        fb.local_set(c)
        fb.local_get(c)
        fb.i32_const(46)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.global_get(dt_pos)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.global_set(dt_pos)
        fb.local_get(ptr)
        fb.local_get(len_v)
        _call(fb, self.helpers["$dt_frac"])
        fb.local_set(nanos)
        fb.emit_end()
        fb.emit_end()
        fb.emit_end()

        # Timezone offset ('Z', '+', '-')
        fb.global_get(dt_ok)
        fb.emit_if()
        fb.global_get(dt_pos)
        fb.local_get(len_v)
        fb.byte(OP_I32_LT_U)
        fb.emit_if()
        fb.local_get(ptr)
        fb.global_get(dt_pos)
        fb.byte(OP_I32_ADD)
        _mem(fb, OP_I32_LOAD8_U, 0, 0)
        fb.local_set(c)
        fb.local_get(c)
        fb.i32_const(90)
        fb.byte(OP_I32_EQ)
        fb.emit_if()
        fb.global_get(dt_pos)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.global_set(dt_pos)
        fb.emit_else()
        fb.local_get(c)
        fb.i32_const(43)
        fb.byte(OP_I32_EQ)
        fb.local_get(c)
        fb.i32_const(45)
        fb.byte(OP_I32_EQ)
        fb.byte(OP_I32_OR)
        fb.emit_if()
        fb.i32_const(1)
        fb.i32_const(0)
        fb.local_get(c)
        fb.i32_const(45)
        fb.byte(OP_I32_EQ)
        fb.byte(OP_SELECT)
        fb.local_set(cneg)
        fb.global_get(dt_pos)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.global_set(dt_pos)
        fb.local_get(ptr)
        fb.local_get(len_v)
        fb.local_get(cneg)
        _call(fb, self.helpers["$dt_offset"])
        fb.local_set(delta)
        fb.emit_end()
        fb.emit_end()
        fb.emit_end()
        fb.emit_end()

        # Skip trailing whitespace
        fb.emit_block()
        b_tws = fb.label_depth
        fb.emit_loop()
        l_tws = fb.label_depth
        fb.global_get(dt_pos)
        fb.local_get(len_v)
        fb.byte(OP_I32_GE_U)
        fb.br_if(_br_depth(fb, b_tws))
        fb.local_get(ptr)
        fb.global_get(dt_pos)
        fb.byte(OP_I32_ADD)
        _mem(fb, OP_I32_LOAD8_U, 0, 0)
        fb.local_set(c)
        fb.local_get(c)
        fb.i32_const(32)
        fb.byte(OP_I32_EQ)
        fb.local_get(c)
        fb.i32_const(9)
        fb.byte(OP_I32_EQ)
        fb.byte(OP_I32_OR)
        fb.emit_if()
        fb.global_get(dt_pos)
        fb.i32_const(1)
        fb.byte(OP_I32_ADD)
        fb.global_set(dt_pos)
        fb.br(_br_depth(fb, l_tws))
        fb.emit_else()
        fb.br(_br_depth(fb, b_tws))
        fb.emit_end()
        fb.emit_end()
        fb.emit_end()

        # Verify end of string reached
        fb.global_get(dt_ok)
        fb.emit_if()
        fb.global_get(dt_pos)
        fb.local_get(len_v)
        fb.byte(OP_I32_NE)
        fb.emit_if()
        fb.i32_const(0)
        fb.global_set(dt_ok)
        fb.emit_end()
        fb.emit_end()

        fb.global_get(dt_ok)
        fb.byte(OP_I32_EQZ)
        fb.emit_if()
        fb.i64_const(0)
        fb.byte(OP_RETURN)
        fb.emit_end()

        # day = days_from_civil(y, mo, d)
        fb.local_get(y)
        fb.local_get(mo)
        fb.local_get(d)
        _call(fb, self.helpers["$days_from_civil"])
        fb.local_set(day)

        # secs = day * 86400 + h * 3600 + mi * 60 + s - delta
        fb.local_get(day)
        fb.i64_const(86400)
        fb.byte(OP_I64_MUL)
        fb.local_get(h)
        fb.i64_const(3600)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_I64_ADD)
        fb.local_get(mi)
        fb.i64_const(60)
        fb.byte(OP_I64_MUL)
        fb.byte(OP_I64_ADD)
        fb.local_get(s)
        fb.byte(OP_I64_ADD)
        fb.local_get(delta)
        fb.byte(OP_I64_SUB)
        fb.local_set(secs)

        # return secs * 1000000000 + nanos
        fb.local_get(secs)
        fb.i64_const(1000000000)
        fb.byte(OP_I64_MUL)
        fb.local_get(nanos)
        fb.byte(OP_I64_ADD)
        fb.byte(OP_RETURN)
        self.add_code(fb)

    def build_all(self) -> None:
        sigs = {
            "$dt_floor_div": ([I64, I64], [I64]),
            "$dt_floor_rem": ([I64, I64], [I64]),
            "$dt_split": ([I64], []),
            "$dt_is_leap_year_val": ([I64], [I64]),
            "$dt_days_in_month_val": ([I64, I64], [I64]),
            "$dt_get_comp": ([I64, I32], [I64]),
            "$dt_create_date": ([I64, I64, I64], [I64]),
            "$dt_create_time": ([I64, I64, I64], [I64]),
            "$dt_create_time_full": ([I64, I64, I64, I64, I64, I64], [I64]),
            "$dt_now": ([], [I64]),
            "$dt_monotonic_now": ([], [I64]),
            "$dt_today": ([], [I64]),
            "$dt_time": ([], [I64]),
            "$dt_add_months": ([I64, I64], [I64]),
            "$dt_add_years": ([I64, I64], [I64]),
            "$dt_months_between": ([I64, I64], [I64]),
            "$dt_years_between": ([I64, I64], [I64]),
            "$dt_write_2d": ([I32, I64], []),
            "$dt_write_4d": ([I32, I64], []),
            "$dt_to_iso": ([I64], [I64]),
            "$dt_to_timezone": ([I64, I64], [I64]),
            "$dt_utc_offset": ([I64, I64], [F64]),
            "$dt_format": ([I64, I64], [I64]),
            "$dt_format_duration": ([I64], [I64]),
            "$dt_parse_iso": ([I64], [I64]),
        }

        for k, (params, results) in sigs.items():
            self.add(k, params, results)

        self.build_dt_floor_div()
        self.build_dt_floor_rem()
        self.build_dt_split()
        self.build_dt_is_leap_year_val()
        self.build_dt_days_in_month_val()
        self.build_dt_get_comp()
        self.build_dt_create_date()
        self.build_dt_create_time()
        self.build_dt_create_time_full()
        self.build_dt_now()
        self.build_dt_monotonic_now()
        self.build_dt_today()
        self.build_dt_time()
        self.build_dt_add_months()
        self.build_dt_add_years()
        self.build_dt_months_between()
        self.build_dt_years_between()
        self.build_dt_write_2d()
        self.build_dt_write_4d()
        self.build_dt_to_iso()
        self.build_dt_to_timezone()
        self.build_dt_utc_offset()
        self.build_dt_format()
        self.build_dt_format_duration()
        self.build_dt_parse_iso()
