from __future__ import annotations

LIST_HELPERS: str = r"""  (func $list_len (param $p i32) (result i32)
    (return (i32.load (local.get $p))))
  (func $list_etag (param $p i32) (result i32)
    (return (i32.load (i32.add (local.get $p) (i32.const 8)))))
  (func $list_row_addr (param $p i32) (param $i1 i32) (result i32)
    (return (i32.add (i32.load (i32.add (local.get $p) (i32.const 12))) (i32.mul (i32.sub (local.get $i1) (i32.const 1)) (i32.const 16)))))
  (func $list_row_tag (param $p i32) (param $i1 i32) (result i32)
    (return (i32.load (call $list_row_addr (local.get $p) (local.get $i1)))))
  (func $list_row_val (param $p i32) (param $i1 i32) (result i64)
    (return (i64.load (i32.add (call $list_row_addr (local.get $p) (local.get $i1)) (i32.const 8)))))
  (func $list_set_row (param $p i32) (param $i1 i32) (param $tag i32) (param $val i64)
    (local $addr i32)
    (local.set $addr (call $list_row_addr (local.get $p) (local.get $i1)))
    (i32.store (local.get $addr) (local.get $tag))
    (i64.store (i32.add (local.get $addr) (i32.const 8)) (local.get $val)))
  (func $list_build (param $n i32) (result i32)
    (local $hdr i32)
    (local $data i32)
    (local $i i32)
    (local $bytes i32)
    (local.set $hdr (call $flux_alloc (i32.const 16)))
    (local.set $bytes (select (i32.mul (local.get $n) (i32.const 16)) (i32.const 16) (i32.gt_u (local.get $n) (i32.const 0))))
    (local.set $data (call $flux_alloc (local.get $bytes)))
    (i32.store (local.get $hdr) (local.get $n))
    (i32.store (i32.add (local.get $hdr) (i32.const 4)) (local.get $n))
    (i32.store (i32.add (local.get $hdr) (i32.const 8)) (i32.const 0))
    (i32.store (i32.add (local.get $hdr) (i32.const 12)) (local.get $data))
    (block $lbdone
      (loop $lbloop
        (br_if $lbdone (i32.ge_u (local.get $i) (local.get $n)))
        (i32.store (i32.add (local.get $data) (i32.mul (local.get $i) (i32.const 16))) (i32.const 0))
        (i64.store (i32.add (i32.add (local.get $data) (i32.mul (local.get $i) (i32.const 16))) (i32.const 8)) (i64.const 0))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $lbloop)))
    (return (local.get $hdr)))
  (func $list_grow (param $p i32)
    (local $newcap i32)
    (local $old i32)
    (local $new i32)
    (local $i i32)
    (local.set $newcap (select (i32.mul (i32.load (i32.add (local.get $p) (i32.const 4))) (i32.const 2)) (i32.const 8) (i32.ge_u (i32.load (i32.add (local.get $p) (i32.const 4))) (i32.const 2))))
    (local.set $old (i32.load (i32.add (local.get $p) (i32.const 12))))
    (local.set $new (call $flux_alloc (i32.mul (local.get $newcap) (i32.const 16))))
    (block $lgdone
      (loop $lgloop
        (br_if $lgdone (i32.ge_u (local.get $i) (i32.load (local.get $p))))
        (i64.store (i32.add (local.get $new) (i32.mul (local.get $i) (i32.const 16))) (i64.load (i32.add (local.get $old) (i32.mul (local.get $i) (i32.const 16)))))
        (i64.store (i32.add (i32.add (local.get $new) (i32.mul (local.get $i) (i32.const 16))) (i32.const 8)) (i64.load (i32.add (i32.add (local.get $old) (i32.mul (local.get $i) (i32.const 16))) (i32.const 8))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $lgloop)))
    (i32.store (i32.add (local.get $p) (i32.const 12)) (local.get $new))
    (i32.store (i32.add (local.get $p) (i32.const 4)) (local.get $newcap)))
  (func $list_push (param $p i32) (param $val i64) (result i32)
    (local $len i32)
    (local $tag i32)
    (local.set $tag (call $list_etag (local.get $p)))
    (if (i32.or (i32.eqz (local.get $tag)) (i32.ge_u (local.get $tag) (i32.const 5))) (then (local.set $tag (i32.const 1))))
    (if (i32.ge_u (i32.load (local.get $p)) (i32.load (i32.add (local.get $p) (i32.const 4)))) (then (call $list_grow (local.get $p))))
    (local.set $len (i32.load (local.get $p)))
    (call $list_set_row (local.get $p) (i32.add (local.get $len) (i32.const 1)) (local.get $tag) (local.get $val))
    (i32.store (local.get $p) (i32.add (local.get $len) (i32.const 1)))
    (return (local.get $p)))
  (func $list_push_row (param $p i32) (param $tag i32) (param $val i64) (result i32)
    (local $len i32)
    (if (i32.ge_u (i32.load (local.get $p)) (i32.load (i32.add (local.get $p) (i32.const 4)))) (then (call $list_grow (local.get $p))))
    (local.set $len (i32.load (local.get $p)))
    (call $list_set_row (local.get $p) (i32.add (local.get $len) (i32.const 1)) (local.get $tag) (local.get $val))
    (i32.store (local.get $p) (i32.add (local.get $len) (i32.const 1)))
    (return (local.get $p)))
  (func $list_push_front (param $p i32) (param $val i64) (result i32)
    (local $tag i32)
    (local $i i32)
    (local.set $tag (call $list_etag (local.get $p)))
    (if (i32.or (i32.eqz (local.get $tag)) (i32.ge_u (local.get $tag) (i32.const 5))) (then (local.set $tag (i32.const 1))))
    (if (i32.ge_u (i32.load (local.get $p)) (i32.load (i32.add (local.get $p) (i32.const 4)))) (then (call $list_grow (local.get $p))))
    (local.set $i (i32.add (i32.load (local.get $p)) (i32.const 1)))
    (block $pfdone
      (loop $pfloop
        (br_if $pfdone (i32.le_u (local.get $i) (i32.const 1)))
        (call $list_set_row (local.get $p) (local.get $i) (call $list_row_tag (local.get $p) (i32.sub (local.get $i) (i32.const 1))) (call $list_row_val (local.get $p) (i32.sub (local.get $i) (i32.const 1))))
        (local.set $i (i32.sub (local.get $i) (i32.const 1)))
        (br $pfloop)))
    (call $list_set_row (local.get $p) (i32.const 1) (local.get $tag) (local.get $val))
    (i32.store (local.get $p) (i32.add (i32.load (local.get $p)) (i32.const 1)))
    (return (local.get $p)))
  (func $list_insert_at (param $p i32) (param $i1 i32) (param $val i64) (result i32)
    (local $tag i32)
    (local $i i32)
    (local.set $tag (call $list_etag (local.get $p)))
    (if (i32.or (i32.eqz (local.get $tag)) (i32.ge_u (local.get $tag) (i32.const 5))) (then (local.set $tag (i32.const 1))))
    (if (i32.gt_u (local.get $i1) (i32.add (i32.load (local.get $p)) (i32.const 1))) (then (return (i32.const 0))))
    (if (i32.ge_u (i32.load (local.get $p)) (i32.load (i32.add (local.get $p) (i32.const 4)))) (then (call $list_grow (local.get $p))))
    (local.set $i (i32.load (local.get $p)))
    (block $iidone
      (loop $iiloop
        (br_if $iidone (i32.lt_u (local.get $i) (local.get $i1)))
        (call $list_set_row (local.get $p) (i32.add (local.get $i) (i32.const 1)) (call $list_row_tag (local.get $p) (local.get $i)) (call $list_row_val (local.get $p) (local.get $i)))
        (local.set $i (i32.sub (local.get $i) (i32.const 1)))
        (br $iiloop)))
    (call $list_set_row (local.get $p) (local.get $i1) (local.get $tag) (local.get $val))
    (i32.store (local.get $p) (i32.add (i32.load (local.get $p)) (i32.const 1)))
    (return (local.get $p)))
  (func $list_remove_at (param $p i32) (param $i1 i32) (result i32)
    (local $i i32)
    (local $n i32)
    (local.set $n (i32.load (local.get $p)))
    (if (i32.gt_u (local.get $i1) (local.get $n)) (then (return (local.get $p))))
    (local.set $i (local.get $i1))
    (block $radone
      (loop $raloop
        (br_if $radone (i32.ge_u (local.get $i) (local.get $n)))
        (call $list_set_row (local.get $p) (local.get $i) (call $list_row_tag (local.get $p) (i32.add (local.get $i) (i32.const 1))) (call $list_row_val (local.get $p) (i32.add (local.get $i) (i32.const 1))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $raloop)))
    (i32.store (local.get $p) (i32.sub (local.get $n) (i32.const 1)))
    (return (local.get $p)))
  (func $list_remove_last (param $p i32) (result i32)
    (if (i32.gt_u (i32.load (local.get $p)) (i32.const 0)) (then (i32.store (local.get $p) (i32.sub (i32.load (local.get $p)) (i32.const 1)))))
    (return (local.get $p)))
  (func $list_clear (param $p i32) (result i32)
    (i32.store (local.get $p) (i32.const 0))
    (return (local.get $p)))
  (func $str_eq (param $a i64) (param $b i64) (result i32)
    (local $la i32)
    (local $lb i32)
    (local $pa i32)
    (local $pb i32)
    (local $i i32)
    (local.set $la (i32.wrap_i64 (local.get $a)))
    (local.set $lb (i32.wrap_i64 (local.get $b)))
    (if (i32.ne (local.get $la) (local.get $lb))
      (then (return (i32.const 0))))
    (local.set $pa (i32.wrap_i64 (i64.shr_u (local.get $a) (i64.const 32))))
    (local.set $pb (i32.wrap_i64 (i64.shr_u (local.get $b) (i64.const 32))))
    (block $eqdone
      (loop $eqloop
        (br_if $eqdone (i32.ge_u (local.get $i) (local.get $la)))
        (if (i32.ne (i32.load8_u (i32.add (local.get $pa) (local.get $i))) (i32.load8_u (i32.add (local.get $pb) (local.get $i))))
          (then (return (i32.const 0))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $eqloop)))
    (return (i32.const 1)))
  (func $elem_eq (param $ta i32) (param $va i64) (param $tb i32) (param $vb i64) (result i32)
    (if (i32.ne (local.get $ta) (local.get $tb))
      (then (return (i32.const 0))))
    (if (i32.eq (local.get $ta) (i32.const 4))
      (then (return (call $str_eq (local.get $va) (local.get $vb)))))
    (return (i64.eq (local.get $va) (local.get $vb))))
  (func $list_contains (param $p i32) (param $val i64) (result i32)
    (local $i i32)
    (local $n i32)
    (local $tag i32)
    (local $etag i32)
    (local.set $n (i32.load (local.get $p)))
    (local.set $etag (call $list_etag (local.get $p)))
    (block $codone
      (loop $coloop
        (br_if $codone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $tag (call $list_row_tag (local.get $p) (local.get $i)))
        (if (i32.or (i32.or (i32.eqz (local.get $etag)) (i32.ge_u (local.get $etag) (i32.const 5))) (i32.eq (local.get $tag) (local.get $etag)))
          (then
            (if (call $elem_eq (local.get $tag) (call $list_row_val (local.get $p) (local.get $i)) (local.get $tag) (local.get $val))
              (then (return (i32.const 1))))))
        (br $coloop)))
    (return (i32.const 0)))
  (func $list_slice (param $p i32) (param $s i32) (param $e i32) (result i32)
    (local $out i32)
    (local $n i32)
    (local $i i32)
    (local.set $n (i32.load (local.get $p)))
    (if (i32.lt_u (local.get $s) (i32.const 1)) (then unreachable))
    (if (i32.gt_u (local.get $e) (local.get $n)) (then unreachable))
    (if (i32.gt_u (local.get $s) (local.get $e)) (then unreachable))
    (local.set $out (call $list_build (i32.add (i32.sub (local.get $e) (local.get $s)) (i32.const 1))))
    (i32.store (i32.add (local.get $out) (i32.const 8)) (call $list_etag (local.get $p)))
    (local.set $i (local.get $s))
    (block $sldone
      (loop $slloop
        (br_if $sldone (i32.gt_u (local.get $i) (local.get $e)))
        (call $list_set_row (local.get $out) (i32.add (i32.sub (local.get $i) (local.get $s)) (i32.const 1)) (call $list_row_tag (local.get $p) (local.get $i)) (call $list_row_val (local.get $p) (local.get $i)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $slloop)))
    (return (local.get $out)))
  (func $swap_rows (param $p i32) (param $i i32) (param $j i32)
    (local $t i32)
    (local $tval i64)
    (local.set $t (call $list_row_tag (local.get $p) (local.get $i)))
    (local.set $tval (call $list_row_val (local.get $p) (local.get $i)))
    (call $list_set_row (local.get $p) (local.get $i) (call $list_row_tag (local.get $p) (local.get $j)) (call $list_row_val (local.get $p) (local.get $j)))
    (call $list_set_row (local.get $p) (local.get $j) (local.get $t) (local.get $tval)))
  (func $str_lt (param $a i64) (param $b i64) (result i32)
    (local $i i32)
    (local $la i32)
    (local $lb i32)
    (local $ca i32)
    (local $cb i32)
    (local.set $la (i32.wrap_i64 (local.get $a)))
    (local.set $lb (i32.wrap_i64 (local.get $b)))
    (block $sldone
      (loop $slloop
        (if (i32.ge_u (local.get $i) (local.get $la))
          (then
            (if (i32.ge_u (local.get $i) (local.get $lb))
              (then (return (i32.const 0)))
              (else (return (i32.const 1)))))
        )
        (if (i32.ge_u (local.get $i) (local.get $lb)) (then (return (i32.const 0))))
        (local.set $ca (i32.load8_u (i32.add (i32.wrap_i64 (i64.shr_u (local.get $a) (i64.const 32))) (local.get $i))))
        (local.set $cb (i32.load8_u (i32.add (i32.wrap_i64 (i64.shr_u (local.get $b) (i64.const 32))) (local.get $i))))
        (if (i32.lt_u (local.get $ca) (local.get $cb)) (then (return (i32.const 1))))
        (if (i32.gt_u (local.get $ca) (local.get $cb)) (then (return (i32.const 0))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $slloop)))
    (return (i32.const 0)))
  (func $elem_lt (param $ta i32) (param $va i64) (param $tb i32) (param $vb i64) (result i32)
    (if (i32.lt_u (local.get $ta) (local.get $tb)) (then (return (i32.const 1))))
    (if (i32.gt_u (local.get $ta) (local.get $tb)) (then (return (i32.const 0))))
    (if (i32.eq (local.get $ta) (i32.const 3)) (then (return (f64.lt (f64.reinterpret_i64 (local.get $va)) (f64.reinterpret_i64 (local.get $vb))))))
    (if (i32.eq (local.get $ta) (i32.const 4)) (then (return (call $str_lt (local.get $va) (local.get $vb)))))
    (return (i64.lt_u (local.get $va) (local.get $vb))))
  (func $list_sort (param $p i32) (param $desc i32)
    (local $i i32)
    (local $j i32)
    (local $n i32)
    (local.set $n (i32.load (local.get $p)))
    (block $stmdone
      (loop $stmloop
        (br_if $stmdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $j (i32.add (local.get $i) (i32.const 1)))
        (block $stjdone
          (loop $stjloop
            (br_if $stjdone (i32.gt_u (local.get $j) (local.get $n)))
            (if (i32.and (i32.eqz (local.get $desc)) (call $elem_lt (call $list_row_tag (local.get $p) (local.get $j)) (call $list_row_val (local.get $p) (local.get $j)) (call $list_row_tag (local.get $p) (local.get $i)) (call $list_row_val (local.get $p) (local.get $i))))
              (then (call $swap_rows (local.get $p) (local.get $i) (local.get $j))))
            (if (i32.and (local.get $desc) (call $elem_lt (call $list_row_tag (local.get $p) (local.get $i)) (call $list_row_val (local.get $p) (local.get $i)) (call $list_row_tag (local.get $p) (local.get $j)) (call $list_row_val (local.get $p) (local.get $j))))
              (then (call $swap_rows (local.get $p) (local.get $i) (local.get $j))))
            (local.set $j (i32.add (local.get $j) (i32.const 1)))
            (br $stjloop)))
        (br $stmloop))
    )
  )
  (func $list_reverse (param $p i32)
    (local $i i32)
    (local $n i32)
    (local.set $n (i32.load (local.get $p)))
    (block $rvdone
      (loop $rvloop
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br_if $rvdone (i32.gt_u (local.get $i) (i32.div_u (local.get $n) (i32.const 2))))
        (call $swap_rows (local.get $p) (local.get $i) (i32.sub (i32.add (local.get $n) (i32.const 1)) (local.get $i)))
        (br $rvloop)))
    )
  (func $list_flatten (param $p i32) (result i32)
    (local $out i32)
    (local $i i32)
    (local $n i32)
    (local $j i32)
    (local $inner i32)
    (local $inlen i32)
    (local.set $out (call $list_build (i32.const 0)))
    (local.set $n (i32.load (local.get $p)))
    (block $fldone
      (loop $flloop
        (br_if $fldone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (if (i32.eq (call $list_row_tag (local.get $p) (local.get $i)) (i32.const 5))
          (then
            (local.set $inner (i32.wrap_i64 (call $list_row_val (local.get $p) (local.get $i))))
            (local.set $j (i32.const 0))
            (local.set $inlen (i32.load (local.get $inner)))
            (block $fldone2
              (loop $flloop2
                (br_if $fldone2 (i32.ge_u (local.get $j) (local.get $inlen)))
                (local.set $j (i32.add (local.get $j) (i32.const 1)))
                (drop (call $list_push_row (local.get $out) (call $list_row_tag (local.get $inner) (local.get $j)) (call $list_row_val (local.get $inner) (local.get $j))))
                (br $flloop2))))
          (else (drop (call $list_push_row (local.get $out) (call $list_row_tag (local.get $p) (local.get $i)) (call $list_row_val (local.get $p) (local.get $i))))))
        (br $flloop)))
    (return (local.get $out)))
  (func $list_partition (param $p i32) (param $size i32) (result i32)
    (local $out i32)
    (local $chunk i32)
    (local $i i32)
    (local $n i32)
    (local $k i32)
    (local.set $n (i32.load (local.get $p)))
    (local.set $out (call $list_build (i32.const 0)))
    (block $ptdone
      (loop $ptloop
        (br_if $ptdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $k (i32.const 0))
        (local.set $chunk (call $list_build (i32.const 0)))
        (block $ptcblk
          (loop $ptcloop
            (br_if $ptcblk (i32.ge_u (local.get $k) (local.get $size)))
            (br_if $ptcblk (i32.ge_u (i32.add (local.get $i) (local.get $k)) (local.get $n)))
            (drop (call $list_push_row (local.get $chunk) (call $list_row_tag (local.get $p) (i32.add (i32.add (local.get $i) (local.get $k)) (i32.const 1))) (call $list_row_val (local.get $p) (i32.add (i32.add (local.get $i) (local.get $k)) (i32.const 1)))))
            (local.set $k (i32.add (local.get $k) (i32.const 1)))
            (br $ptcloop)))
        (local.set $i (i32.add (local.get $i) (local.get $k)))
        (drop (call $list_push_row (local.get $out) (i32.const 5) (i64.extend_i32_u (local.get $chunk))))
        (br $ptloop)))
    (return (local.get $out)))
  (func $list_zip (param $a i32) (param $b i32) (result i32)
    (local $n i32)
    (local $i i32)
    (local $pair i32)
    (local $out i32)
    (local.set $n (call $list_len (local.get $a)))
    (if (i32.lt_u (call $list_len (local.get $b)) (local.get $n)) (then (local.set $n (call $list_len (local.get $b)))))
    (local.set $out (call $list_build (i32.const 0)))
    (block $zpdone
      (loop $zploop
        (br_if $zpdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $pair (call $list_build (i32.const 2)))
        (call $list_set_row (local.get $pair) (i32.const 1) (call $list_row_tag (local.get $a) (local.get $i)) (call $list_row_val (local.get $a) (local.get $i)))
        (call $list_set_row (local.get $pair) (i32.const 2) (call $list_row_tag (local.get $b) (local.get $i)) (call $list_row_val (local.get $b) (local.get $i)))
        (drop (call $list_push_row (local.get $out) (i32.const 5) (i64.extend_i32_u (local.get $pair))))
        (br $zploop)))
    (return (local.get $out)))
  (func $list_unzip (param $p i32) (result i32)
    (local $ls i32)
    (local $rs i32)
    (local $out i32)
    (local $n i32)
    (local $i i32)
    (local $pair i32)
    (local.set $n (i32.load (local.get $p)))
    (local.set $ls (call $list_build (i32.const 0)))
    (local.set $rs (call $list_build (i32.const 0)))
    (block $uzdone
      (loop $uzloop
        (br_if $uzdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $pair (i32.wrap_i64 (call $list_row_val (local.get $p) (local.get $i))))
        (drop (call $list_push_row (local.get $ls) (call $list_row_tag (local.get $pair) (i32.const 1)) (call $list_row_val (local.get $pair) (i32.const 1))))
        (drop (call $list_push_row (local.get $rs) (call $list_row_tag (local.get $pair) (i32.const 2)) (call $list_row_val (local.get $pair) (i32.const 2))))
        (br $uzloop)))
    (local.set $out (call $list_build (i32.const 2)))
    (call $list_set_row (local.get $out) (i32.const 1) (i32.const 5) (i64.extend_i32_u (local.get $ls)))
    (call $list_set_row (local.get $out) (i32.const 2) (i32.const 5) (i64.extend_i32_u (local.get $rs)))
    (return (local.get $out)))
  (func $str_ncopy (param $src i32) (param $len i32) (param $dst i32) (result i32)
    (local $i i32)
    (block $ncdone
      (loop $ncloop
        (br_if $ncdone (i32.ge_u (local.get $i) (local.get $len)))
        (i32.store8 (i32.add (local.get $dst) (local.get $i)) (i32.load8_u (i32.add (local.get $src) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $ncloop)))
    (return (local.get $len)))
  (func $elem_to_str (param $tag i32) (param $val i64) (param $buf i32) (result i32)
    (if (i32.eqz (local.get $tag))
      (then
        (i32.store8 (local.get $buf) (i32.const 78))
        (i32.store8 (i32.add (local.get $buf) (i32.const 1)) (i32.const 111))
        (i32.store8 (i32.add (local.get $buf) (i32.const 2)) (i32.const 110))
        (i32.store8 (i32.add (local.get $buf) (i32.const 3)) (i32.const 101))
        (return (i32.const 4))))
    (if (i32.eq (local.get $tag) (i32.const 4))
      (then (return (call $str_ncopy (i32.wrap_i64 (i64.shr_u (local.get $val) (i64.const 32))) (i32.wrap_i64 (local.get $val)) (local.get $buf)))))
    (if (i32.eq (local.get $tag) (i32.const 5))
      (then
        (if (i32.eq (call $list_etag (i32.wrap_i64 (local.get $val))) (i32.const 7))
          (then (return (call $map_to_str (i32.wrap_i64 (local.get $val)) (local.get $buf)))))
        (if (i32.eq (call $list_etag (i32.wrap_i64 (local.get $val))) (i32.const 6))
          (then (return (call $set_to_str (i32.wrap_i64 (local.get $val)) (local.get $buf)))))
        (return (call $list_to_str (i32.wrap_i64 (local.get $val)) (local.get $buf)))))
    (if (i32.eq (local.get $tag) (i32.const 6))
      (then (return (call $set_to_str (i32.wrap_i64 (local.get $val)) (local.get $buf)))))
    (if (i32.eq (local.get $tag) (i32.const 7))
      (then (return (call $map_to_str (i32.wrap_i64 (local.get $val)) (local.get $buf)))))
    (if (i32.eq (local.get $tag) (i32.const 3))
      (then (return (call $f64_to_str (f64.reinterpret_i64 (local.get $val)) (local.get $buf)))))
    (if (i32.eq (local.get $tag) (i32.const 2))
      (then
        (if (i64.eqz (local.get $val))
          (then
            (i32.store8 (local.get $buf) (i32.const 102))
            (i32.store8 (i32.add (local.get $buf) (i32.const 1)) (i32.const 97))
            (i32.store8 (i32.add (local.get $buf) (i32.const 2)) (i32.const 108))
            (i32.store8 (i32.add (local.get $buf) (i32.const 3)) (i32.const 115))
            (i32.store8 (i32.add (local.get $buf) (i32.const 4)) (i32.const 101))
            (return (i32.const 5)))
          (else
            (i32.store8 (local.get $buf) (i32.const 116))
            (i32.store8 (i32.add (local.get $buf) (i32.const 1)) (i32.const 114))
            (i32.store8 (i32.add (local.get $buf) (i32.const 2)) (i32.const 117))
            (i32.store8 (i32.add (local.get $buf) (i32.const 3)) (i32.const 101))
            (return (i32.const 4))))))
    (return (call $i64_to_str (local.get $val) (local.get $buf))))
  (func $strcpy (param $src i32) (param $dst i32) (result i32)
    (local $i i32)
    (local $c i32)
    (block $scdone
      (loop $scloop
        (local.set $c (i32.load8_u (i32.add (local.get $src) (local.get $i))))
        (br_if $scdone (i32.eqz (local.get $c)))
        (i32.store8 (i32.add (local.get $dst) (local.get $i)) (local.get $c))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $scloop)))
    (i32.store8 (i32.add (local.get $dst) (local.get $i)) (i32.const 0))
    (return (local.get $i)))
  (func $list_to_str (param $p i32) (param $buf i32) (result i32)
    (local $i i32)
    (local $n i32)
    (local $len i32)
    (if (i32.eqz (local.get $p))
      (then
        (i32.store8 (local.get $buf) (i32.const 110))
        (i32.store8 (i32.add (local.get $buf) (i32.const 1)) (i32.const 117))
        (i32.store8 (i32.add (local.get $buf) (i32.const 2)) (i32.const 108))
        (i32.store8 (i32.add (local.get $buf) (i32.const 3)) (i32.const 108))
        (i32.store8 (i32.add (local.get $buf) (i32.const 4)) (i32.const 0))
        (return (i32.const 4))))
    (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 91))
    (local.set $len (i32.add (local.get $len) (i32.const 1)))
    (local.set $n (i32.load (local.get $p)))
    (block $lsdone
      (loop $lsloop
        (br_if $lsdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (if (i32.gt_u (local.get $i) (i32.const 1))
          (then
            (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 44))
            (i32.store8 (i32.add (i32.add (local.get $buf) (local.get $len)) (i32.const 1)) (i32.const 32))
            (local.set $len (i32.add (local.get $len) (i32.const 2)))))
        (local.set $len (i32.add (local.get $len) (call $elem_to_str (call $list_row_tag (local.get $p) (local.get $i)) (call $list_row_val (local.get $p) (local.get $i)) (i32.add (local.get $buf) (local.get $len)))))
        (br $lsloop)))
    (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 93))
    (local.set $len (i32.add (local.get $len) (i32.const 1)))
    (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 0))
    (return (local.get $len)))
  (func $strbuf_new (param $cap i32) (result i32)
    (local $b i32)
    (local.set $b (call $flux_alloc (i32.add (local.get $cap) (i32.const 4))))
    (i32.store (local.get $b) (i32.const 0))
    (return (local.get $b)))
  (func $strappend (param $buf i32) (param $src i64)
    (local $len i32)
    (local $n i32)
    (local $i i32)
    (local $c i32)
    (local.set $len (i32.load (local.get $buf)))
    (local.set $n (i32.wrap_i64 (local.get $src)))
    (block $apdone
      (loop $aploop
        (br_if $apdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $c (i32.load8_u (i32.add (i32.wrap_i64 (i64.shr_u (local.get $src) (i64.const 32))) (local.get $i))))
        (i32.store8 (i32.add (i32.add (local.get $buf) (i32.const 4)) (i32.add (local.get $len) (local.get $i))) (local.get $c))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $aploop)))
    (i32.store (local.get $buf) (i32.add (local.get $len) (local.get $n))))
  (func $strbuf_done (param $buf i32)
    (i32.store8 (i32.add (i32.add (local.get $buf) (i32.const 4)) (i32.load (local.get $buf))) (i32.const 0)))
  (func $list_concat (param $a i32) (param $b i32) (result i32)
    (local $out i32)
    (local $i i32)
    (local $na i32)
    (local $nb i32)
    (local.set $na (call $list_len (local.get $a)))
    (local.set $nb (call $list_len (local.get $b)))
    (local.set $out (call $list_build (i32.add (local.get $na) (local.get $nb))))
    (if (i32.gt_u (local.get $na) (i32.const 0))
      (then (i32.store (i32.add (local.get $out) (i32.const 8)) (call $list_etag (local.get $a))))
      (else (if (i32.gt_u (local.get $nb) (i32.const 0))
        (then (i32.store (i32.add (local.get $out) (i32.const 8)) (call $list_etag (local.get $b)))))))
    (block $ccdone
      (loop $ccloop
        (br_if $ccdone (i32.ge_u (local.get $i) (local.get $na)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (call $list_set_row (local.get $out) (local.get $i) (call $list_row_tag (local.get $a) (local.get $i)) (call $list_row_val (local.get $a) (local.get $i)))
        (br $ccloop)))
    (local.set $i (i32.const 0))
    (block $ccdone2
      (loop $ccloop2
        (br_if $ccdone2 (i32.ge_u (local.get $i) (local.get $nb)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (call $list_set_row (local.get $out) (i32.add (local.get $na) (local.get $i)) (call $list_row_tag (local.get $b) (local.get $i)) (call $list_row_val (local.get $b) (local.get $i)))
        (br $ccloop2)))
    (return (local.get $out)))
  (func $set_build (param $n i32) (param $tag i32) (result i32)
    (local $s i32)
    (local.set $s (call $list_build (local.get $n)))
    (i32.store (local.get $s) (i32.const 0))
    (i32.store (i32.add (local.get $s) (i32.const 8)) (i32.const 6))
    (return (local.get $s)))
  (func $set_contains (param $p i32) (param $tag i32) (param $val i64) (result i32)
    (local $i i32)
    (local $n i32)
    (local.set $n (i32.load (local.get $p)))
    (block $scdone
      (loop $scloop
        (br_if $scdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (if (call $elem_eq (call $list_row_tag (local.get $p) (local.get $i)) (call $list_row_val (local.get $p) (local.get $i)) (local.get $tag) (local.get $val))
          (then (return (i32.const 1))))
        (br $scloop)))
    (return (i32.const 0)))
  (func $set_push (param $p i32) (param $tag i32) (param $val i64) (result i32)
    (if (call $set_contains (local.get $p) (local.get $tag) (local.get $val))
      (then (return (local.get $p))))
    (return (call $list_push_row (local.get $p) (local.get $tag) (local.get $val))))
  (func $set_to_str (param $p i32) (param $buf i32) (result i32)
    (local $i i32)
    (local $n i32)
    (local $len i32)
    (if (i32.eqz (local.get $p))
      (then
        (i32.store8 (local.get $buf) (i32.const 123))
        (i32.store8 (i32.add (local.get $buf) (i32.const 1)) (i32.const 125))
        (i32.store8 (i32.add (local.get $buf) (i32.const 2)) (i32.const 0))
        (return (i32.const 2))))
    (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 123))
    (local.set $len (i32.add (local.get $len) (i32.const 1)))
    (local.set $n (i32.load (local.get $p)))
    (block $ssdone
      (loop $ssloop
        (br_if $ssdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (if (i32.gt_u (local.get $i) (i32.const 1))
          (then
            (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 44))
            (i32.store8 (i32.add (i32.add (local.get $buf) (local.get $len)) (i32.const 1)) (i32.const 32))
            (local.set $len (i32.add (local.get $len) (i32.const 2)))))
        (local.set $len (i32.add (local.get $len) (call $elem_to_str (call $list_row_tag (local.get $p) (local.get $i)) (call $list_row_val (local.get $p) (local.get $i)) (i32.add (local.get $buf) (local.get $len)))))
        (br $ssloop)))
    (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 125))
    (local.set $len (i32.add (local.get $len) (i32.const 1)))
    (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 0))
    (return (local.get $len)))
  (func $set_remove (param $p i32) (param $tag i32) (param $val i64) (result i32)
    (local $i i32)
    (local $n i32)
    (local.set $n (i32.load (local.get $p)))
    (block $srdone
      (loop $srloop
        (br_if $srdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (if (call $elem_eq (call $list_row_tag (local.get $p) (local.get $i)) (call $list_row_val (local.get $p) (local.get $i)) (local.get $tag) (local.get $val))
          (then (return (call $list_remove_at (local.get $p) (local.get $i)))))
        (br $srloop)))
    (return (local.get $p)))
  (func $set_copy_rows (param $src i32) (param $dst i32)
    (local $i i32)
    (local $n i32)
    (local.set $n (i32.load (local.get $src)))
    (block $scrdone
      (loop $scrloop
        (br_if $scrdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (drop (call $set_push (local.get $dst) (call $list_row_tag (local.get $src) (local.get $i)) (call $list_row_val (local.get $src) (local.get $i))))
        (br $scrloop)))
  )
  (func $set_union (param $a i32) (param $b i32) (result i32)
    (local $out i32)
    (local $etag i32)
    (local.set $etag (call $list_etag (local.get $a)))
    (if (i32.eqz (local.get $etag)) (then (local.set $etag (call $list_etag (local.get $b)))))
    (local.set $out (call $set_build (i32.add (call $list_len (local.get $a)) (call $list_len (local.get $b))) (local.get $etag)))
    (call $set_copy_rows (local.get $a) (local.get $out))
    (call $set_copy_rows (local.get $b) (local.get $out))
    (return (local.get $out)))
  (func $set_intersect (param $a i32) (param $b i32) (result i32)
    (local $out i32)
    (local $i i32)
    (local $n i32)
    (local.set $out (call $set_build (i32.const 0) (call $list_etag (local.get $a))))
    (local.set $n (i32.load (local.get $a)))
    (block $sidone
      (loop $siloop
        (br_if $sidone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (if (call $set_contains (local.get $b) (call $list_row_tag (local.get $a) (local.get $i)) (call $list_row_val (local.get $a) (local.get $i)))
          (then (drop (call $set_push (local.get $out) (call $list_row_tag (local.get $a) (local.get $i)) (call $list_row_val (local.get $a) (local.get $i))))))
        (br $siloop)))
    (return (local.get $out)))
  (func $set_difference (param $a i32) (param $b i32) (result i32)
    (local $out i32)
    (local $i i32)
    (local $n i32)
    (local.set $out (call $set_build (i32.const 0) (call $list_etag (local.get $a))))
    (local.set $n (i32.load (local.get $a)))
    (block $sfdone
      (loop $sfloop
        (br_if $sfdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (if (i32.eqz (call $set_contains (local.get $b) (call $list_row_tag (local.get $a) (local.get $i)) (call $list_row_val (local.get $a) (local.get $i))))
          (then (drop (call $set_push (local.get $out) (call $list_row_tag (local.get $a) (local.get $i)) (call $list_row_val (local.get $a) (local.get $i))))))
        (br $sfloop)))
    (return (local.get $out)))
  (func $set_symmetric_difference (param $a i32) (param $b i32) (result i32)
    (local $out i32)
    (local $i i32)
    (local $n i32)
    (local.set $out (call $set_difference (local.get $a) (local.get $b)))
    (local.set $n (i32.load (local.get $b)))
    (block $sxdone
      (loop $sxloop
        (br_if $sxdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (if (i32.eqz (call $set_contains (local.get $a) (call $list_row_tag (local.get $b) (local.get $i)) (call $list_row_val (local.get $b) (local.get $i))))
          (then (drop (call $set_push (local.get $out) (call $list_row_tag (local.get $b) (local.get $i)) (call $list_row_val (local.get $b) (local.get $i))))))
        (br $sxloop)))
    (return (local.get $out)))
  (func $set_is_subset (param $a i32) (param $b i32) (result i32)
    (local $i i32)
    (local $n i32)
    (local.set $n (i32.load (local.get $a)))
    (block $sbsdone
      (loop $sbsloop
        (br_if $sbsdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (if (i32.eqz (call $set_contains (local.get $b) (call $list_row_tag (local.get $a) (local.get $i)) (call $list_row_val (local.get $a) (local.get $i))))
          (then (return (i32.const 0))))
        (br $sbsloop)))
    (return (i32.const 1)))
  (func $set_is_superset (param $a i32) (param $b i32) (result i32)
    (return (call $set_is_subset (local.get $b) (local.get $a))))
  (func $set_is_disjoint (param $a i32) (param $b i32) (result i32)
    (local $i i32)
    (local $n i32)
    (local.set $n (i32.load (local.get $a)))
    (block $sjdone
      (loop $sjloop
        (br_if $sjdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (if (call $set_contains (local.get $b) (call $list_row_tag (local.get $a) (local.get $i)) (call $list_row_val (local.get $a) (local.get $i)))
          (then (return (i32.const 0))))
        (br $sjloop)))
    (return (i32.const 1)))
  (func $set_to_list (param $p i32) (result i32)
    (local $out i32)
    (local $i i32)
    (local $n i32)
    (local.set $n (i32.load (local.get $p)))
    (local.set $out (call $list_build (local.get $n)))
    (i32.store (i32.add (local.get $out) (i32.const 8)) (call $list_etag (local.get $p)))
    (block $sldone
      (loop $slloop
        (br_if $sldone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (call $list_set_row (local.get $out) (local.get $i) (call $list_row_tag (local.get $p) (local.get $i)) (call $list_row_val (local.get $p) (local.get $i)))
        (br $slloop)))
    (return (local.get $out)))
  (func $list_to_set (param $p i32) (result i32)
    (local $s i32)
    (local.set $s (call $set_build (call $list_len (local.get $p)) (call $list_etag (local.get $p))))
    (call $set_copy_rows (local.get $p) (local.get $s))
    (return (local.get $s)))
  (func $set_eq (param $a i32) (param $b i32) (result i32)
    (if (i32.ne (i32.load (local.get $a)) (i32.load (local.get $b))) (then (return (i32.const 0))))
    (return (call $set_is_subset (local.get $a) (local.get $b))))
  (func $list_eq (param $a i32) (param $b i32) (result i32)
    (local $i i32)
    (local $n i32)
    (if (i32.ne (i32.load (local.get $a)) (i32.load (local.get $b))) (then (return (i32.const 0))))
    (local.set $n (i32.load (local.get $a)))
    (block $leqdone
      (loop $leqloop
        (br_if $leqdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (if (i32.eqz (call $elem_eq (call $list_row_tag (local.get $a) (local.get $i)) (call $list_row_val (local.get $a) (local.get $i)) (call $list_row_tag (local.get $b) (local.get $i)) (call $list_row_val (local.get $b) (local.get $i))))
          (then (return (i32.const 0))))
        (br $leqloop)))
    (return (i32.const 1)))
  (func $map_grow (param $p i32)
    (local $newcap i32)
    (local $old i32)
    (local $new i32)
    (local $i i32)
    (local $off i32)
    (local.set $newcap (select (i32.mul (i32.load (i32.add (local.get $p) (i32.const 4))) (i32.const 2)) (i32.const 4) (i32.ge_u (i32.load (i32.add (local.get $p) (i32.const 4))) (i32.const 2))))
    (local.set $old (i32.load (i32.add (local.get $p) (i32.const 12))))
    (local.set $new (call $flux_alloc (i32.mul (local.get $newcap) (i32.const 20))))
    (block $mgdone
      (loop $mgloop
        (br_if $mgdone (i32.ge_u (local.get $i) (i32.load (local.get $p))))
        (local.set $off (i32.mul (local.get $i) (i32.const 20)))
        (i64.store (i32.add (local.get $new) (local.get $off)) (i64.load (i32.add (local.get $old) (local.get $off))))
        (i32.store (i32.add (i32.add (local.get $new) (local.get $off)) (i32.const 8)) (i32.load (i32.add (i32.add (local.get $old) (local.get $off)) (i32.const 8))))
        (i64.store (i32.add (i32.add (local.get $new) (local.get $off)) (i32.const 12)) (i64.load (i32.add (i32.add (local.get $old) (local.get $off)) (i32.const 12))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $mgloop)))
    (i32.store (i32.add (local.get $p) (i32.const 12)) (local.get $new))
    (i32.store (i32.add (local.get $p) (i32.const 4)) (local.get $newcap)))
  (func $map_row_addr (param $p i32) (param $i1 i32) (result i32)
    (i32.add (i32.load (i32.add (local.get $p) (i32.const 12))) (i32.mul (i32.sub (local.get $i1) (i32.const 1)) (i32.const 20)))
    )
  (func $map_find (param $p i32) (param $kfat i64) (result i32)
    (local $i i32)
    (local $n i32)
    (local $addr i32)
    (local.set $n (i32.load (local.get $p)))
    (block $findone
      (loop $findloop
        (br_if $findone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $addr (call $map_row_addr (local.get $p) (local.get $i)))
        (if (call $str_eq (i64.load (local.get $addr)) (local.get $kfat))
          (then (return (local.get $i))))
        (br $findloop)))
    (return (i32.const 0)))
  (func $map_set (param $p i32) (param $kfat i64) (param $vtag i32) (param $vval i64) (result i32)
    (local $idx i32)
    (local $addr i32)
    (local.set $idx (call $map_find (local.get $p) (local.get $kfat)))
    (if (i32.eqz (local.get $idx))
      (then
        (call $map_grow (local.get $p))
        (local.set $idx (i32.add (i32.load (local.get $p)) (i32.const 1)))
        (i32.store (local.get $p) (local.get $idx))))
    (local.set $addr (call $map_row_addr (local.get $p) (local.get $idx)))
    (i64.store (local.get $addr) (local.get $kfat))
    (i32.store (i32.add (local.get $addr) (i32.const 8)) (local.get $vtag))
    (i64.store (i32.add (local.get $addr) (i32.const 12)) (local.get $vval))
    (return (local.get $p)))
  (func $map_set_if_absent (param $p i32) (param $kfat i64) (param $vtag i32) (param $vval i64) (result i32)
    (if (call $map_find (local.get $p) (local.get $kfat))
      (then (return (local.get $p))))
    (return (call $map_set (local.get $p) (local.get $kfat) (local.get $vtag) (local.get $vval))))
  (func $map_replace (param $p i32) (param $kfat i64) (param $vtag i32) (param $vval i64) (result i32)
    (local $idx i32)
    (local.set $idx (call $map_find (local.get $p) (local.get $kfat)))
    (if (i32.eqz (local.get $idx))
      (then (return (call $map_set (local.get $p) (local.get $kfat) (local.get $vtag) (local.get $vval)))))
    (i32.store (i32.add (call $map_row_addr (local.get $p) (local.get $idx)) (i32.const 8)) (local.get $vtag))
    (i64.store (i32.add (call $map_row_addr (local.get $p) (local.get $idx)) (i32.const 12)) (local.get $vval))
    (return (local.get $p)))
  (func $map_remove (param $p i32) (param $kfat i64) (result i32)
    (local $idx i32)
    (local $n i32)
    (local $i i32)
    (local $dst i32)
    (local $src i32)
    (local.set $idx (call $map_find (local.get $p) (local.get $kfat)))
    (if (i32.eqz (local.get $idx))
      (then (return (local.get $p))))
    (local.set $n (i32.load (local.get $p)))
    (i32.store (local.get $p) (i32.sub (local.get $n) (i32.const 1)))
    (local.set $i (local.get $idx))
    (block $rmdone
      (loop $rmloop
        (br_if $rmdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $dst (call $map_row_addr (local.get $p) (local.get $i)))
        (local.set $src (call $map_row_addr (local.get $p) (i32.add (local.get $i) (i32.const 1))))
        (i64.store (local.get $dst) (i64.load (local.get $src)))
        (i32.store (i32.add (local.get $dst) (i32.const 8)) (i32.load (i32.add (local.get $src) (i32.const 8))))
        (i64.store (i32.add (local.get $dst) (i32.const 12)) (i64.load (i32.add (local.get $src) (i32.const 12))))
        (br $rmloop)))
    (return (local.get $p)))
  (func $map_get (param $p i32) (param $kfat i64) (result i64)
    (local $idx i32)
    (local.set $idx (call $map_find (local.get $p) (local.get $kfat)))
    (if (i32.eqz (local.get $idx))
      (then (return (i64.const 0))))
    (return (i64.load (i32.add (call $map_row_addr (local.get $p) (local.get $idx)) (i32.const 12)))))
  (func $map_get_tag (param $p i32) (param $kfat i64) (result i32)
    (local $idx i32)
    (local.set $idx (call $map_find (local.get $p) (local.get $kfat)))
    (if (i32.eqz (local.get $idx))
      (then (return (i32.const 0))))
    (return (i32.load (i32.add (call $map_row_addr (local.get $p) (local.get $idx)) (i32.const 8)))))
  (func $map_contains_key (param $p i32) (param $kfat i64) (result i32)
    (return (i32.ne (call $map_find (local.get $p) (local.get $kfat)) (i32.const 0))))
  (func $map_contains_value (param $p i32) (param $vtag i32) (param $vval i64) (result i32)
    (local $i i32)
    (local $n i32)
    (local $addr i32)
    (local.set $n (i32.load (local.get $p)))
    (block $cvdone
      (loop $cvloop
        (br_if $cvdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $addr (call $map_row_addr (local.get $p) (local.get $i)))
        (if (call $elem_eq (i32.load (i32.add (local.get $addr) (i32.const 8))) (i64.load (i32.add (local.get $addr) (i32.const 12))) (local.get $vtag) (local.get $vval))
          (then (return (i32.const 1))))
        (br $cvloop)))
    (return (i32.const 0)))
  (func $map_clear (param $p i32) (result i32)
    (i32.store (local.get $p) (i32.const 0))
    (return (local.get $p)))
  (func $map_keys (param $p i32) (result i32)
    (local $out i32)
    (local $i i32)
    (local $n i32)
    (local.set $n (i32.load (local.get $p)))
    (local.set $out (call $list_build (local.get $n)))
    (i32.store (i32.add (local.get $out) (i32.const 8)) (i32.const 4))
    (block $mkdone
      (loop $mkloop
        (br_if $mkdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (call $list_set_row (local.get $out) (local.get $i) (i32.const 4) (i64.load (call $map_row_addr (local.get $p) (local.get $i))))
        (br $mkloop)))
    (return (local.get $out)))
  (func $map_values (param $p i32) (result i32)
    (local $out i32)
    (local $i i32)
    (local $n i32)
    (local $addr i32)
    (local.set $n (i32.load (local.get $p)))
    (local.set $out (call $list_build (local.get $n)))
    (block $mvdone
      (loop $mvloop
        (br_if $mvdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $addr (call $map_row_addr (local.get $p) (local.get $i)))
        (call $list_set_row (local.get $out) (local.get $i) (i32.load (i32.add (local.get $addr) (i32.const 8))) (i64.load (i32.add (local.get $addr) (i32.const 12))))
        (br $mvloop)))
    (return (local.get $out)))
  (func $map_entries (param $p i32) (result i32)
    (local $out i32)
    (local $i i32)
    (local $n i32)
    (local $addr i32)
    (local $inner i32)
    (local.set $n (i32.load (local.get $p)))
    (local.set $out (call $list_build (local.get $n)))
    (block $meone
      (loop $meloop
        (br_if $meone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $addr (call $map_row_addr (local.get $p) (local.get $i)))
        (local.set $inner (call $list_build (i32.const 2)))
        (call $list_set_row (local.get $inner) (i32.const 1) (i32.const 4) (i64.load (local.get $addr)))
        (call $list_set_row (local.get $inner) (i32.const 2) (i32.load (i32.add (local.get $addr) (i32.const 8))) (i64.load (i32.add (local.get $addr) (i32.const 12))))
        (call $list_set_row (local.get $out) (local.get $i) (i32.const 5) (i64.extend_i32_u (local.get $inner)))
        (br $meloop)))
    (return (local.get $out)))
  (func $map_merge (param $a i32) (param $b i32) (result i32)
    (local $out i32)
    (local $i i32)
    (local $n i32)
    (local $addr i32)
    (local.set $n (i32.load (local.get $a)))
    (local.set $out (call $map_build (local.get $n)))
    (block $mmdone
      (loop $mmloop
        (br_if $mmdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $addr (call $map_row_addr (local.get $a) (local.get $i)))
        (drop (call $map_set (local.get $out) (i64.load (local.get $addr)) (i32.load (i32.add (local.get $addr) (i32.const 8))) (i64.load (i32.add (local.get $addr) (i32.const 12)))))
        (br $mmloop)))
    (local.set $n (i32.load (local.get $b)))
    (local.set $i (i32.const 0))
    (block $mmdone2
      (loop $mmloop2
        (br_if $mmdone2 (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $addr (call $map_row_addr (local.get $b) (local.get $i)))
        (drop (call $map_set (local.get $out) (i64.load (local.get $addr)) (i32.load (i32.add (local.get $addr) (i32.const 8))) (i64.load (i32.add (local.get $addr) (i32.const 12)))))
        (br $mmloop2)))
    (return (local.get $out)))
  (func $map_to_str (param $p i32) (param $buf i32) (result i32)
    (local $i i32)
    (local $n i32)
    (local $len i32)
    (local $addr i32)
    (local.set $n (i32.load (local.get $p)))
    (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 123))
    (local.set $len (i32.add (local.get $len) (i32.const 1)))
    (block $mtsdone
      (loop $mtsloop
        (br_if $mtsdone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $addr (call $map_row_addr (local.get $p) (local.get $i)))
        (if (i32.gt_u (local.get $i) (i32.const 1))
          (then
            (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 44))
            (i32.store8 (i32.add (i32.add (local.get $buf) (local.get $len)) (i32.const 1)) (i32.const 32))
            (local.set $len (i32.add (local.get $len) (i32.const 2)))))
        (local.set $len (i32.add (local.get $len) (call $elem_to_str (i32.const 4) (i64.load (local.get $addr)) (i32.add (local.get $buf) (local.get $len)))))
        (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 58))
        (i32.store8 (i32.add (i32.add (local.get $buf) (local.get $len)) (i32.const 1)) (i32.const 32))
        (local.set $len (i32.add (local.get $len) (i32.const 2)))
        (local.set $len (i32.add (local.get $len) (call $elem_to_str (i32.load (i32.add (local.get $addr) (i32.const 8))) (i64.load (i32.add (local.get $addr) (i32.const 12))) (i32.add (local.get $buf) (local.get $len)))))
        (br $mtsloop)))
    (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 125))
    (local.set $len (i32.add (local.get $len) (i32.const 1)))
    (i32.store8 (i32.add (local.get $buf) (local.get $len)) (i32.const 0))
    (return (local.get $len)))
  (func $map_to_set (param $p i32) (result i32)
    (local $s i32)
    (local $i i32)
    (local $n i32)
    (local.set $n (i32.load (local.get $p)))
    (local.set $s (call $set_build (local.get $n) (i32.const 4)))
    (block $mtso
      (loop $mtsl
        (br_if $mtso (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (drop (call $set_push (local.get $s) (i32.const 4) (i64.load (call $map_row_addr (local.get $p) (local.get $i)))))
        (br $mtsl)))
    (return (local.get $s)))
  (func $map_from_pairs (param $p i32) (result i32)
    (local $out i32)
    (local $i i32)
    (local $n i32)
    (local $inner i32)
    (local.set $n (i32.load (local.get $p)))
    (local.set $out (call $map_build (i32.const 0)))
    (block $mfpone
      (loop $mfploop
        (br_if $mfpone (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $inner (i32.wrap_i64 (call $list_row_val (local.get $p) (local.get $i))))
        (drop (call $map_set (local.get $out) (call $list_row_val (local.get $inner) (i32.const 1)) (call $list_row_tag (local.get $inner) (i32.const 2)) (call $list_row_val (local.get $inner) (i32.const 2))))
        (br $mfploop)))
    (return (local.get $out)))
  (func $collection_to_str (param $p i32) (param $buf i32) (result i32)
    (if (i32.eqz (local.get $p))
      (then
        (i32.store8 (local.get $buf) (i32.const 78))
        (i32.store8 (i32.add (local.get $buf) (i32.const 1)) (i32.const 111))
        (i32.store8 (i32.add (local.get $buf) (i32.const 2)) (i32.const 110))
        (i32.store8 (i32.add (local.get $buf) (i32.const 3)) (i32.const 101))
        (return (i32.const 4))))
    (if (i32.lt_u (local.get $p) (global.get $flux_heap_start))
      (then (return (call $i64_to_str (i64.extend_i32_u (local.get $p)) (local.get $buf)))))
    (if (i32.eq (i32.load (i32.add (local.get $p) (i32.const 8))) (i32.const 7))
      (then (return (call $map_to_str (local.get $p) (local.get $buf)))))
    (if (i32.eq (i32.load (i32.add (local.get $p) (i32.const 8))) (i32.const 6))
      (then (return (call $set_to_str (local.get $p) (local.get $buf)))))
    (return (call $list_to_str (local.get $p) (local.get $buf))))
  (func $list_set_grow (param $p i32) (param $i1 i32) (param $tag i32) (param $val i64) (result i32)
    (local $n i32)
    (local.set $n (i32.load (local.get $p)))
    (if (i32.eq (local.get $i1) (i32.add (local.get $n) (i32.const 1)))
      (then (return (call $list_push_row (local.get $p) (local.get $tag) (local.get $val)))))
    (if (i32.le_u (local.get $i1) (local.get $n))
      (then
        (call $list_set_row (local.get $p) (local.get $i1) (local.get $tag) (local.get $val))
        (return (local.get $p))))
    (unreachable))
  (func $map_build (param $n i32) (result i32)
    (local $h i32)
    (local.set $h (call $list_build (i32.const 0)))
    (i32.store (i32.add (local.get $h) (i32.const 8)) (i32.const 7))
    (return (local.get $h)))
  (func $tensor_rec (param $p i32) (param $dim i32) (param $base i32) (param $buf i32) (param $cur i32) (param $tag i32) (result i32)
    (local $n i32)
    (local $j i32)
    (local $st i32)
    (local $dptr i32)
    (local $rank i32)
    (local.set $rank (i32.load (local.get $p)))
    (i32.store8 (i32.add (local.get $buf) (local.get $cur)) (i32.const 91))
    (local.set $cur (i32.add (local.get $cur) (i32.const 1)))
    (local.set $n (i32.load (i32.add (local.get $p) (i32.mul (i32.add (local.get $dim) (i32.const 1)) (i32.const 4)))))
    (local.set $st (i32.load (i32.add (local.get $p) (i32.mul (i32.add (i32.add (local.get $rank) (local.get $dim)) (i32.const 1)) (i32.const 4)))))
    (local.set $dptr (i32.load (i32.add (local.get $p) (i32.mul (i32.add (i32.mul (local.get $rank) (i32.const 2)) (i32.const 1)) (i32.const 4)))))
    (if (i32.eq (local.get $dim) (i32.sub (local.get $rank) (i32.const 1)))
      (then
        (block $tedone
          (loop $teloop
            (br_if $tedone (i32.ge_u (local.get $j) (local.get $n)))
            (if (i32.gt_u (local.get $j) (i32.const 0))
              (then
                (i32.store8 (i32.add (local.get $buf) (local.get $cur)) (i32.const 44))
                (i32.store8 (i32.add (i32.add (local.get $buf) (local.get $cur)) (i32.const 1)) (i32.const 32))
                (local.set $cur (i32.add (local.get $cur) (i32.const 2)))))
            (local.set $cur (i32.add (local.get $cur) (call $elem_to_str (local.get $tag) (i64.load (i32.add (local.get $dptr) (i32.mul (i32.add (local.get $base) (i32.mul (local.get $j) (local.get $st))) (i32.const 8)))) (i32.add (local.get $buf) (local.get $cur)))))
            (local.set $j (i32.add (local.get $j) (i32.const 1)))
            (br $teloop))))
      (else
        (block $tddone
          (loop $tdloop
            (br_if $tddone (i32.ge_u (local.get $j) (local.get $n)))
            (if (i32.gt_u (local.get $j) (i32.const 0))
              (then
                (i32.store8 (i32.add (local.get $buf) (local.get $cur)) (i32.const 44))
                (i32.store8 (i32.add (i32.add (local.get $buf) (local.get $cur)) (i32.const 1)) (i32.const 32))
                (local.set $cur (i32.add (local.get $cur) (i32.const 2)))))
            (local.set $cur (call $tensor_rec (local.get $p) (i32.add (local.get $dim) (i32.const 1)) (i32.add (local.get $base) (i32.mul (local.get $j) (local.get $st))) (local.get $buf) (local.get $cur) (local.get $tag)))
            (local.set $j (i32.add (local.get $j) (i32.const 1)))
            (br $tdloop)))))
    (i32.store8 (i32.add (local.get $buf) (local.get $cur)) (i32.const 93))
    (return (i32.add (local.get $cur) (i32.const 1))))
  (func $tensor_to_str (param $p i32) (param $buf i32) (param $tag i32) (result i32)
    (return (call $tensor_rec (local.get $p) (i32.const 0) (i32.const 0) (local.get $buf) (i32.const 0) (local.get $tag))))
  (func $tensor_mat (param $src i32) (result i32)
    ;; Copia tensor/view para buffer próprio contíguo.
    ;; Linear→coords: kᵢ = (L / sᵢ) mod dᵢ ; coords→linear destino: Σ kᵢ·Sᵢ(row-major)
    (local $rank i32)
    (local $hdr i32)
    (local $prod i32)
    (local $k i32)
    (local $d i32)
    (local $sd i32)
    (local $dst i32)
    (local $L i32)
    (local $soff i32)
    (local $sdst i32)
    (local.set $rank (i32.load (local.get $src)))
    (local.set $hdr (i32.mul (i32.add (local.get $rank) (i32.const 1)) (i32.const 8)))
    (local.set $prod (i32.const 1))
    (local.set $k (i32.const 0))
    (block $pd (loop $pl
      (br_if $pd (i32.ge_u (local.get $k) (local.get $rank)))
      (local.set $prod (i32.mul (local.get $prod) (i32.load (i32.add (local.get $src) (i32.mul (i32.add (local.get $k) (i32.const 1)) (i32.const 4))))))
      (local.set $k (i32.add (local.get $k) (i32.const 1)))
      (br $pl)))
    (local.set $dst (call $flux_alloc (i32.add (local.get $hdr) (i32.mul (local.get $prod) (i32.const 8)))))
    (i32.store (local.get $dst) (local.get $rank))
    ;; dims copiam do src; strides destino = row-major derivada
    (local.set $sdst (i32.const 1))
    (local.set $k (local.get $rank))
    (block $sd (loop $sl
      (br_if $sd (i32.eqz (local.get $k)))
      (local.set $k (i32.sub (local.get $k) (i32.const 1)))
      (local.set $d (i32.load (i32.add (local.get $src) (i32.mul (i32.add (local.get $k) (i32.const 1)) (i32.const 4)))))
      (i32.store (i32.add (local.get $dst) (i32.mul (i32.add (local.get $k) (i32.const 1)) (i32.const 4))) (local.get $d))
      (i32.store (i32.add (local.get $dst) (i32.mul (i32.add (i32.add (local.get $rank) (local.get $k)) (i32.const 1)) (i32.const 4))) (local.get $sdst))
      (local.set $sdst (i32.mul (local.get $sdst) (local.get $d)))
      (br $sl)))
    (i32.store (i32.add (local.get $dst) (i32.mul (i32.add (i32.mul (local.get $rank) (i32.const 2)) (i32.const 1)) (i32.const 4))) (i32.add (local.get $dst) (local.get $hdr)))
    ;; cópia: L linear destino → coords via strides fonte
    (local.set $L (i32.const 0))
    (block $cd (loop $cl
      (br_if $cd (i32.ge_u (local.get $L) (local.get $prod)))
      (local.set $soff (i32.const 0))
      (local.set $k (i32.const 0))
      (block $kd (loop $kl
        (br_if $kd (i32.ge_u (local.get $k) (local.get $rank)))
        (local.set $sd (i32.load (i32.add (local.get $src) (i32.mul (i32.add (i32.add (local.get $rank) (local.get $k)) (i32.const 1)) (i32.const 4)))))
        (local.set $soff (i32.add (local.get $soff)
          (i32.mul (i32.rem_u (i32.div_u (local.get $L) (local.get $sd)) (i32.load (i32.add (local.get $src) (i32.mul (i32.add (local.get $k) (i32.const 1)) (i32.const 4))))))
                   (local.get $sd)))
        (local.set $k (i32.add (local.get $k) (i32.const 1)))
        (br $kl)))
      (i64.store
        (i32.add (i32.add (local.get $dst) (local.get $hdr)) (i32.mul (local.get $L) (i32.const 8)))
        (i64.load (i32.add
          (i32.load (i32.add (local.get $src) (i32.mul (i32.add (i32.mul (local.get $rank) (i32.const 2)) (i32.const 1)) (i32.const 4))))
          (i32.mul (local.get $soff) (i32.const 8)))))
      (local.set $L (i32.add (local.get $L) (i32.const 1)))
      (br $cl)))
    (return (local.get $dst)))
  (func $dt_to_str (param $nanos i64) (param $buf i32) (result i32)
    (local $sec i64) (local $frac i64) (local $days i64) (local $rem_sec i64)
    (local $hour i64) (local $min i64) (local $s i64)
    (local $z i64) (local $era i64) (local $doe i64) (local $yoe i64) (local $y i64)
    (local $doy i64) (local $mp i64) (local $d i64) (local $m i64)
    (local $p i32)
    (local.set $sec (i64.div_s (local.get $nanos) (i64.const 1000000000)))
    (local.set $frac (i64.rem_s (local.get $nanos) (i64.const 1000000000)))
    (local.set $days (i64.div_s (local.get $sec) (i64.const 86400)))
    (local.set $rem_sec (i64.rem_s (local.get $sec) (i64.const 86400)))
    (local.set $hour (i64.div_s (local.get $rem_sec) (i64.const 3600)))
    (local.set $min (i64.div_s (i64.rem_s (local.get $rem_sec) (i64.const 3600)) (i64.const 60)))
    (local.set $s (i64.rem_s (local.get $rem_sec) (i64.const 60)))
    (local.set $z (i64.add (local.get $days) (i64.const 719468)))
    (local.set $era (i64.div_s (local.get $z) (i64.const 146097)))
    (local.set $doe (i64.sub (local.get $z) (i64.mul (local.get $era) (i64.const 146097))))
    (local.set $yoe (i64.div_s (i64.add (i64.sub (i64.sub (local.get $doe) (i64.div_s (local.get $doe) (i64.const 1460))) (i64.div_s (local.get $doe) (i64.const 36524))) (i64.div_s (local.get $doe) (i64.const 146096))) (i64.const 365)))
    (local.set $y (i64.add (local.get $yoe) (i64.mul (local.get $era) (i64.const 400))))
    (local.set $doy (i64.sub (local.get $doe) (i64.sub (i64.add (i64.mul (i64.const 365) (local.get $yoe)) (i64.div_s (local.get $yoe) (i64.const 4))) (i64.div_s (local.get $yoe) (i64.const 100)))))
    (local.set $mp (i64.div_s (i64.add (i64.mul (i64.const 5) (local.get $doy)) (i64.const 2)) (i64.const 153)))
    (local.set $d (i64.add (i64.sub (local.get $doy) (i64.div_s (i64.add (i64.mul (i64.const 153) (local.get $mp)) (i64.const 2)) (i64.const 5))) (i64.const 1)))
    (local.set $m (select (i64.add (local.get $mp) (i64.const 3)) (i64.sub (local.get $mp) (i64.const 9)) (i64.lt_s (local.get $mp) (i64.const 10))))
    (if (i64.le_s (local.get $m) (i64.const 2)) (then (local.set $y (i64.add (local.get $y) (i64.const 1)))))
    (local.set $p (local.get $buf))
    (i32.store8 (local.get $p) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (i64.div_s (local.get $y) (i64.const 1000)) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 1)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (i64.div_s (local.get $y) (i64.const 100)) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 2)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (i64.div_s (local.get $y) (i64.const 10)) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 3)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (local.get $y) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 4)) (i32.const 45))
    (i32.store8 (i32.add (local.get $p) (i32.const 5)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.div_s (local.get $m) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 6)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (local.get $m) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 7)) (i32.const 45))
    (i32.store8 (i32.add (local.get $p) (i32.const 8)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.div_s (local.get $d) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 9)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (local.get $d) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 10)) (i32.const 84))
    (i32.store8 (i32.add (local.get $p) (i32.const 11)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.div_s (local.get $hour) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 12)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (local.get $hour) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 13)) (i32.const 58))
    (i32.store8 (i32.add (local.get $p) (i32.const 14)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.div_s (local.get $min) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 15)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (local.get $min) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 16)) (i32.const 58))
    (i32.store8 (i32.add (local.get $p) (i32.const 17)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.div_s (local.get $s) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 18)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (local.get $s) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 19)) (i32.const 46))
    (i32.store8 (i32.add (local.get $p) (i32.const 20)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (i64.div_s (local.get $frac) (i64.const 100000000)) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 21)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (i64.div_s (local.get $frac) (i64.const 10000000)) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 22)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (i64.div_s (local.get $frac) (i64.const 1000000)) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 23)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (i64.div_s (local.get $frac) (i64.const 100000)) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 24)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (i64.div_s (local.get $frac) (i64.const 10000)) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 25)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (i64.div_s (local.get $frac) (i64.const 1000)) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 26)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (i64.div_s (local.get $frac) (i64.const 100)) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 27)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (i64.div_s (local.get $frac) (i64.const 10)) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 28)) (i32.wrap_i64 (i64.add (i64.const 48) (i64.rem_s (local.get $frac) (i64.const 10)))))
    (i32.store8 (i32.add (local.get $p) (i32.const 29)) (i32.const 90))
    (return (i32.const 30)))
  (func $str_char_len (param $p i32) (result i32)
    (local $i i32)
    (local $n i32)
    (local.set $i (i32.const 0))
    (local.set $n (i32.const 0))
    (block $done
      (loop $loop
        (br_if $done (i32.eqz (i32.load8_u (i32.add (local.get $p) (local.get $i)))))
        (if (i32.ne (i32.and (i32.load8_u (i32.add (local.get $p) (local.get $i))) (i32.const 192)) (i32.const 128))
          (then (local.set $n (i32.add (local.get $n) (i32.const 1)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop)))
    (return (local.get $n)))
  (func $str_slice (param $p i32) (param $s i32) (param $e i32) (result i32)
    (local $tot i32)
    (local $soff i32)
    (local $eoff i32)
    (local $cp i32)
    (local $i i32)
    (local $out i32)
    (local $j i32)
    (local.set $tot (call $str_char_len (local.get $p)))
    (if (i32.lt_u (local.get $s) (i32.const 1)) (then unreachable))
    (if (i32.gt_u (local.get $e) (local.get $tot)) (then unreachable))
    (if (i32.gt_u (local.get $s) (local.get $e)) (then unreachable))
    (local.set $i (i32.const 0))
    (local.set $cp (i32.const 0))
    (block $sdone
      (loop $sloop
        (br_if $sdone (i32.ge_u (local.get $cp) (i32.sub (local.get $s) (i32.const 1))))
        (br_if $sdone (i32.eqz (i32.load8_u (i32.add (local.get $p) (local.get $i)))))
        (if (i32.ne (i32.and (i32.load8_u (i32.add (local.get $p) (local.get $i))) (i32.const 192)) (i32.const 128))
          (then (local.set $cp (i32.add (local.get $cp) (i32.const 1)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $sloop)))
    (local.set $soff (local.get $i))
    (block $edone
      (loop $eloop
        (br_if $edone (i32.ge_u (local.get $cp) (local.get $e)))
        (br_if $edone (i32.eqz (i32.load8_u (i32.add (local.get $p) (local.get $i)))))
        (if (i32.ne (i32.and (i32.load8_u (i32.add (local.get $p) (local.get $i))) (i32.const 192)) (i32.const 128))
          (then (local.set $cp (i32.add (local.get $cp) (i32.const 1)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $eloop)))
    (local.set $eoff (local.get $i))
    (local.set $out (call $flux_alloc (i32.add (i32.sub (local.get $eoff) (local.get $soff)) (i32.const 1))))
    (local.set $j (local.get $soff))
    (block $cdone
      (loop $cloop
        (br_if $cdone (i32.ge_u (local.get $j) (local.get $eoff)))
        (i32.store8 (i32.add (local.get $out) (i32.sub (local.get $j) (local.get $soff)))
          (i32.load8_u (i32.add (local.get $p) (local.get $j))))
        (local.set $j (i32.add (local.get $j) (i32.const 1)))
        (br $cloop)))
    (i32.store8 (i32.add (local.get $out) (i32.sub (local.get $eoff) (local.get $soff))) (i32.const 0))
    (return (local.get $out)))
  (func $str_slice_fat (param $h i64) (param $s i32) (param $e i32) (result i64)
    (local $p i32)
    (local $r i32)
    (local.set $p (i32.wrap_i64 (i64.shr_u (local.get $h) (i64.const 32))))
    (local.set $r (call $str_slice (local.get $p) (local.get $s) (local.get $e)))
    (return (i64.or (i64.shl (i64.extend_i32_u (local.get $r)) (i64.const 32))
                    (i64.extend_i32_u (i32.add (i32.sub (local.get $e) (local.get $s)) (i32.const 1))))))
  (func $str_to_list (param $s i64) (result i32)
    (local $ptr i32) (local $len i32) (local $out i32) (local $i i32) (local $c i32) (local $clen i32) (local $char_ptr i32) (local $fat i64)
    (local.set $ptr (i32.wrap_i64 (i64.shr_u (local.get $s) (i64.const 32))))
    (local.set $len (i32.wrap_i64 (local.get $s)))
    (local.set $out (call $list_build (i32.const 0)))
    (i32.store (i32.add (local.get $out) (i32.const 8)) (i32.const 4))
    (block $done (loop $loop
      (br_if $done (i32.ge_u (local.get $i) (local.get $len)))
      (local.set $c (i32.load8_u (i32.add (local.get $ptr) (local.get $i))))
      (local.set $clen (select (i32.const 1) (select (i32.const 2) (select (i32.const 3) (i32.const 4) (i32.ge_u (local.get $c) (i32.const 240))) (i32.ge_u (local.get $c) (i32.const 224))) (i32.lt_u (local.get $c) (i32.const 192))))
      (local.set $char_ptr (i32.add (local.get $ptr) (local.get $i)))
      (local.set $fat (i64.or (i64.shl (i64.extend_i32_u (local.get $char_ptr)) (i64.const 32)) (i64.extend_i32_u (local.get $clen))))
      (drop (call $list_push_row (local.get $out) (i32.const 4) (local.get $fat)))
      (local.set $i (i32.add (local.get $i) (local.get $clen)))
      (br $loop)))
    (return (local.get $out)))
  (func $val_to_list_dyn (param $val i64) (param $tag i32) (result i32)
    (local $p i32) (local $out i32)
    (if (i32.eq (local.get $tag) (i32.const 4)) (then (return (call $str_to_list (local.get $val)))))
    (local.set $p (i32.wrap_i64 (local.get $val)))
    (if (i32.and (i64.eqz (i64.shr_u (local.get $val) (i64.const 32))) (i32.ge_u (local.get $p) (global.get $flux_heap_start)))
      (then
        (if (i32.eq (call $list_etag (local.get $p)) (i32.const 6)) (then (return (call $set_to_list (local.get $p)))))
        (return (local.get $p))))
    (if (i32.gt_u (i32.wrap_i64 (i64.shr_u (local.get $val) (i64.const 32))) (i32.const 0))
      (then (return (call $str_to_list (local.get $val)))))
    (local.set $out (call $list_build (i32.const 1)))
    (call $list_set_row (local.get $out) (i32.const 1) (local.get $tag) (local.get $val))
    (return (local.get $out)))
  (func $val_to_set_dyn (param $val i64) (param $tag i32) (result i32)
    (local $p i32) (local $s i32)
    (if (i32.eq (local.get $tag) (i32.const 4)) (then (return (call $list_to_set (call $str_to_list (local.get $val))))))
    (local.set $p (i32.wrap_i64 (local.get $val)))
    (if (i32.and (i64.eqz (i64.shr_u (local.get $val) (i64.const 32))) (i32.ge_u (local.get $p) (global.get $flux_heap_start)))
      (then
        (if (i32.eq (call $list_etag (local.get $p)) (i32.const 6)) (then (return (local.get $p))))
        (return (call $list_to_set (local.get $p)))))
    (if (i32.gt_u (i32.wrap_i64 (i64.shr_u (local.get $val) (i64.const 32))) (i32.const 0))
      (then (return (call $list_to_set (call $str_to_list (local.get $val))))))
    (local.set $s (call $set_build (i32.const 1) (local.get $tag)))
    (drop (call $set_push (local.get $s) (local.get $tag) (local.get $val)))
    (return (local.get $s)))
  (func $val_to_str_dyn (param $val i64) (param $buf i32) (result i32)
    (local $p i32)
    (local $hi i32)
    (local.set $hi (i32.wrap_i64 (i64.shr_u (local.get $val) (i64.const 32))))
    (if (i32.and (i32.gt_u (local.get $hi) (i32.const 0)) (i32.lt_u (local.get $hi) (i32.const 0x70000000)))
      (then
        (return (call $str_ncopy (local.get $hi) (i32.wrap_i64 (local.get $val)) (local.get $buf)))))
    (local.set $p (i32.wrap_i64 (local.get $val)))
    (if (i32.ge_u (local.get $p) (global.get $flux_heap_start))
      (then
        (if (i32.eq (call $list_etag (local.get $p)) (i32.const 7))
          (then (return (call $map_to_str (local.get $p) (local.get $buf)))))
        (if (i32.eq (call $list_etag (local.get $p)) (i32.const 6))
          (then (return (call $set_to_str (local.get $p) (local.get $buf)))))
        (return (call $list_to_str (local.get $p) (local.get $buf)))))
    (return (call $i64_to_str (local.get $val) (local.get $buf))))
"""
