from __future__ import annotations

SIMD_HELPERS: str = r"""  (func $simd_extract_double (param $p i32) (param $i1 i32) (result f64)
    (return (f64.reinterpret_i64 (call $list_row_val (local.get $p) (local.get $i1)))))

  (func $simd_vector_binop (param $a i32) (param $b i32) (param $op i32) (param $is_f32 i32) (result i32)
    (local $na i32)
    (local $nb i32)
    (local $n i32)
    (local $out i32)
    (local $i i32)
    (local $va f64)
    (local $vb f64)
    (local $res f64)
    (local $fa f32)
    (local $fb f32)
    (local $fres f32)
    (if (i32.or (i32.eqz (local.get $a)) (i32.eqz (local.get $b)))
      (then (return (call $list_build (i32.const 0)))))
    (local.set $na (call $list_len (local.get $a)))
    (local.set $nb (call $list_len (local.get $b)))
    (local.set $n (select (local.get $na) (local.get $nb) (i32.lt_u (local.get $na) (local.get $nb))))
    (local.set $out (call $list_build (local.get $n)))
    (i32.store (i32.add (local.get $out) (i32.const 8)) (i32.const 3))
    (local.set $i (i32.const 1))
    (block $done
      (loop $lp
        (br_if $done (i32.gt_u (local.get $i) (local.get $n)))
        (local.set $va (call $simd_extract_double (local.get $a) (local.get $i)))
        (local.set $vb (call $simd_extract_double (local.get $b) (local.get $i)))
        (if (local.get $is_f32)
          (then
            (local.set $fa (f32.demote_f64 (local.get $va)))
            (local.set $fb (f32.demote_f64 (local.get $vb)))
            (if (i32.eq (local.get $op) (i32.const 0))
              (then (local.set $fres (f32.add (local.get $fa) (local.get $fb)))))
            (if (i32.eq (local.get $op) (i32.const 1))
              (then (local.set $fres (f32.sub (local.get $fa) (local.get $fb)))))
            (if (i32.eq (local.get $op) (i32.const 2))
              (then (local.set $fres (f32.mul (local.get $fa) (local.get $fb)))))
            (if (i32.eq (local.get $op) (i32.const 3))
              (then (local.set $fres (select (f32.div (local.get $fa) (local.get $fb)) (f32.const 0) (f32.ne (local.get $fb) (f32.const 0))))))
            (local.set $res (f64.promote_f32 (local.get $fres))))
          (else
            (if (i32.eq (local.get $op) (i32.const 0))
              (then (local.set $res (f64.add (local.get $va) (local.get $vb)))))
            (if (i32.eq (local.get $op) (i32.const 1))
              (then (local.set $res (f64.sub (local.get $va) (local.get $vb)))))
            (if (i32.eq (local.get $op) (i32.const 2))
              (then (local.set $res (f64.mul (local.get $va) (local.get $vb)))))
            (if (i32.eq (local.get $op) (i32.const 3))
              (then (local.set $res (select (f64.div (local.get $va) (local.get $vb)) (f64.const 0) (f64.ne (local.get $vb) (f64.const 0))))))))
        (call $list_set_row (local.get $out) (local.get $i) (i32.const 3) (i64.reinterpret_f64 (local.get $res)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $lp)))
    (return (local.get $out)))

  (func $simd_dot_product (param $a i32) (param $b i32) (param $is_f32 i32) (result f64)
    (local $na i32)
    (local $nb i32)
    (local $n i32)
    (local $i i32)
    (local $va f64)
    (local $vb f64)
    (local $sum f64)
    (if (i32.or (i32.eqz (local.get $a)) (i32.eqz (local.get $b)))
      (then (return (f64.const 0))))
    (local.set $na (call $list_len (local.get $a)))
    (local.set $nb (call $list_len (local.get $b)))
    (local.set $n (select (local.get $na) (local.get $nb) (i32.lt_u (local.get $na) (local.get $nb))))
    (local.set $i (i32.const 1))
    (local.set $sum (f64.const 0))
    (block $done
      (loop $lp
        (br_if $done (i32.gt_u (local.get $i) (local.get $n)))
        (local.set $va (call $simd_extract_double (local.get $a) (local.get $i)))
        (local.set $vb (call $simd_extract_double (local.get $b) (local.get $i)))
        (local.set $sum (f64.add (local.get $sum) (f64.mul (local.get $va) (local.get $vb))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $lp)))
    (if (local.get $is_f32)
      (then (return (f64.promote_f32 (f32.demote_f64 (local.get $sum))))))
    (return (local.get $sum)))

  (func $simd_vector_sum (param $a i32) (param $is_f32 i32) (result f64)
    (local $n i32)
    (local $i i32)
    (local $sum f64)
    (if (i32.eqz (local.get $a))
      (then (return (f64.const 0))))
    (local.set $n (call $list_len (local.get $a)))
    (local.set $i (i32.const 1))
    (local.set $sum (f64.const 0))
    (block $done
      (loop $lp
        (br_if $done (i32.gt_u (local.get $i) (local.get $n)))
        (local.set $sum (f64.add (local.get $sum) (call $simd_extract_double (local.get $a) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $lp)))
    (if (local.get $is_f32)
      (then (return (f64.promote_f32 (f32.demote_f64 (local.get $sum))))))
    (return (local.get $sum)))

  (func $simd_vector_clamp (param $a i32) (param $min_v f64) (param $max_v f64) (param $is_f32 i32) (result i32)
    (local $n i32)
    (local $out i32)
    (local $i i32)
    (local $v f64)
    (if (i32.eqz (local.get $a))
      (then (return (call $list_build (i32.const 0)))))
    (local.set $n (call $list_len (local.get $a)))
    (local.set $out (call $list_build (local.get $n)))
    (i32.store (i32.add (local.get $out) (i32.const 8)) (i32.const 3))
    (local.set $i (i32.const 1))
    (block $done
      (loop $lp
        (br_if $done (i32.gt_u (local.get $i) (local.get $n)))
        (local.set $v (call $simd_extract_double (local.get $a) (local.get $i)))
        (if (f64.lt (local.get $v) (local.get $min_v))
          (then (local.set $v (local.get $min_v))))
        (if (f64.gt (local.get $v) (local.get $max_v))
          (then (local.set $v (local.get $max_v))))
        (if (local.get $is_f32)
          (then (local.set $v (f64.promote_f32 (f32.demote_f64 (local.get $v))))))
        (call $list_set_row (local.get $out) (local.get $i) (i32.const 3) (i64.reinterpret_f64 (local.get $v)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $lp)))
    (return (local.get $out)))

  (func $simd_select (param $mask i32) (param $a i32) (param $b i32) (param $is_f32 i32) (result i32)
    (local $nm i32)
    (local $na i32)
    (local $nb i32)
    (local $n i32)
    (local $out i32)
    (local $i i32)
    (local $m i64)
    (local $v f64)
    (if (i32.or (i32.or (i32.eqz (local.get $mask)) (i32.eqz (local.get $a))) (i32.eqz (local.get $b)))
      (then (return (call $list_build (i32.const 0)))))
    (local.set $nm (call $list_len (local.get $mask)))
    (local.set $na (call $list_len (local.get $a)))
    (local.set $nb (call $list_len (local.get $b)))
    (local.set $n (select (local.get $nm) (local.get $na) (i32.lt_u (local.get $nm) (local.get $na))))
    (if (i32.lt_u (local.get $nb) (local.get $n))
      (then (local.set $n (local.get $nb))))
    (local.set $out (call $list_build (local.get $n)))
    (i32.store (i32.add (local.get $out) (i32.const 8)) (i32.const 3))
    (local.set $i (i32.const 1))
    (block $done
      (loop $lp
        (br_if $done (i32.gt_u (local.get $i) (local.get $n)))
        (local.set $m (call $list_row_val (local.get $mask) (local.get $i)))
        (if (i64.ne (local.get $m) (i64.const 0))
          (then (local.set $v (call $simd_extract_double (local.get $a) (local.get $i))))
          (else (local.set $v (call $simd_extract_double (local.get $b) (local.get $i)))))
        (if (local.get $is_f32)
          (then (local.set $v (f64.promote_f32 (f32.demote_f64 (local.get $v))))))
        (call $list_set_row (local.get $out) (local.get $i) (i32.const 3) (i64.reinterpret_f64 (local.get $v)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $lp)))
    (return (local.get $out)))

  (func $simd_matrix_mul_2d (param $lhs i32) (param $rhs i32) (param $is_f32 i32) (param $k_ndim i64) (param $k_shape i64) (param $k_strides i64) (param $k_offset i64) (param $k_data i64) (result i32)
    (local $shape_l i32)
    (local $shape_r i32)
    (local $data_l i32)
    (local $data_r i32)
    (local $rows_l i32)
    (local $cols_l i32)
    (local $rows_r i32)
    (local $cols_r i32)
    (local $total_out i32)
    (local $out_data i32)
    (local $out_shape i32)
    (local $out_strides i32)
    (local $out_map i32)
    (local $i i32)
    (local $j i32)
    (local $k i32)
    (local $sum f64)
    (local $vl f64)
    (local $vr f64)
    (local $idx_l i32)
    (local $idx_r i32)
    (local $idx_out i32)
    (if (i32.or (i32.eqz (local.get $lhs)) (i32.eqz (local.get $rhs)))
      (then (return (call $map_build (i32.const 0)))))
    (local.set $shape_l (i32.wrap_i64 (call $map_get (local.get $lhs) (local.get $k_shape))))
    (local.set $shape_r (i32.wrap_i64 (call $map_get (local.get $rhs) (local.get $k_shape))))
    (local.set $data_l (i32.wrap_i64 (call $map_get (local.get $lhs) (local.get $k_data))))
    (local.set $data_r (i32.wrap_i64 (call $map_get (local.get $rhs) (local.get $k_data))))
    (local.set $rows_l (i32.const 1))
    (local.set $cols_l (i32.const 1))
    (if (local.get $shape_l)
      (then
        (if (i32.ge_u (call $list_len (local.get $shape_l)) (i32.const 1))
          (then (local.set $rows_l (i32.wrap_i64 (call $list_row_val (local.get $shape_l) (i32.const 1))))))
        (if (i32.ge_u (call $list_len (local.get $shape_l)) (i32.const 2))
          (then (local.set $cols_l (i32.wrap_i64 (call $list_row_val (local.get $shape_l) (i32.const 2))))))))
    (local.set $rows_r (i32.const 1))
    (local.set $cols_r (i32.const 1))
    (if (local.get $shape_r)
      (then
        (if (i32.ge_u (call $list_len (local.get $shape_r)) (i32.const 1))
          (then (local.set $rows_r (i32.wrap_i64 (call $list_row_val (local.get $shape_r) (i32.const 1))))))
        (if (i32.ge_u (call $list_len (local.get $shape_r)) (i32.const 2))
          (then (local.set $cols_r (i32.wrap_i64 (call $list_row_val (local.get $shape_r) (i32.const 2))))))))
    (local.set $total_out (i32.mul (local.get $rows_l) (local.get $cols_r)))
    (local.set $out_data (call $list_build (local.get $total_out)))
    (i32.store (i32.add (local.get $out_data) (i32.const 8)) (i32.const 3))
    (local.set $i (i32.const 0))
    (block $done_i
      (loop $lp_i
        (br_if $done_i (i32.ge_u (local.get $i) (local.get $rows_l)))
        (local.set $j (i32.const 0))
        (block $done_j
          (loop $lp_j
            (br_if $done_j (i32.ge_u (local.get $j) (local.get $cols_r)))
            (local.set $sum (f64.const 0))
            (local.set $k (i32.const 0))
            (block $done_k
              (loop $lp_k
                (br_if $done_k (i32.ge_u (local.get $k) (local.get $cols_l)))
                (local.set $idx_l (i32.add (i32.add (i32.mul (local.get $i) (local.get $cols_l)) (local.get $k)) (i32.const 1)))
                (local.set $idx_r (i32.add (i32.add (i32.mul (local.get $k) (local.get $cols_r)) (local.get $j)) (i32.const 1)))
                (local.set $vl (call $simd_extract_double (local.get $data_l) (local.get $idx_l)))
                (local.set $vr (call $simd_extract_double (local.get $data_r) (local.get $idx_r)))
                (local.set $sum (f64.add (local.get $sum) (f64.mul (local.get $vl) (local.get $vr))))
                (local.set $k (i32.add (local.get $k) (i32.const 1)))
                (br $lp_k)))
            (if (local.get $is_f32)
              (then (local.set $sum (f64.promote_f32 (f32.demote_f64 (local.get $sum))))))
            (local.set $idx_out (i32.add (i32.add (i32.mul (local.get $i) (local.get $cols_r)) (local.get $j)) (i32.const 1)))
            (call $list_set_row (local.get $out_data) (local.get $idx_out) (i32.const 3) (i64.reinterpret_f64 (local.get $sum)))
            (local.set $j (i32.add (local.get $j) (i32.const 1)))
            (br $lp_j)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $lp_i)))
    (local.set $out_shape (call $list_build (i32.const 2)))
    (call $list_set_row (local.get $out_shape) (i32.const 1) (i32.const 0) (i64.extend_i32_u (local.get $rows_l)))
    (call $list_set_row (local.get $out_shape) (i32.const 2) (i32.const 0) (i64.extend_i32_u (local.get $cols_r)))
    (local.set $out_strides (call $list_build (i32.const 2)))
    (call $list_set_row (local.get $out_strides) (i32.const 1) (i32.const 0) (i64.extend_i32_u (local.get $cols_r)))
    (call $list_set_row (local.get $out_strides) (i32.const 2) (i32.const 0) (i64.const 1))
    (local.set $out_map (call $map_build (i32.const 0)))
    (drop (call $map_set (local.get $out_map) (local.get $k_ndim) (i32.const 0) (i64.const 2)))
    (drop (call $map_set (local.get $out_map) (local.get $k_shape) (i32.const 5) (i64.extend_i32_u (local.get $out_shape))))
    (drop (call $map_set (local.get $out_map) (local.get $k_strides) (i32.const 5) (i64.extend_i32_u (local.get $out_strides))))
    (drop (call $map_set (local.get $out_map) (local.get $k_offset) (i32.const 0) (i64.const 1)))
    (drop (call $map_set (local.get $out_map) (local.get $k_data) (i32.const 5) (i64.extend_i32_u (local.get $out_data))))
    (return (local.get $out_map)))
"""
